[freetz-stable-1.1] Merge in r3459, r3470, r3472, r3476, r3478, r3480, r3483:r3487, r3491:r3493, r3497:r3501, r3505:r3506, r3509:r3510, r3512, r3515, r3517:r3518, r3520, r3523:r3525, r3527:r3533, r3542:r3543 from trunk:  * firmwares:   * add support for 7270 v3, firmware version 74.04.76   * 7170: version bump to 29.04.76    * Alien 3170, 7140, 7141, W701V, W900V: adapt patches for new firmware versio    * correct kernel source for international versions    * fix typos    * 7270: 04.76 has webdav plugin     * 7270 plugins: Move kernel modules located in AVM plugins to standard modules dir  * kernel:   * 7270, 7240: Add new (04.76) kernel source, reactivate replace kernel   * 7170: Add new (04.76) kernel source, reactivate replace kernel  * packages:   * cpmaccfg: bump to version 0.6 with better support for tantos chipsets (F!B 7270)   * dnsmasq: Start multid with desired flags   * inotify: Add hint to wiki article    * improper usage can lead to reboots   * openntpd: Start multid with correct flags (refs #346)    * autoselect "remove chronyd"    * add hint about listening interface   * privoxy: Add missing option --disable-zlib, add missing subopts   * rrdstats: fix "month"-view  * patches:   * 7113: Fix remove websrv patch (by er13)   * Fix reverse search (130-foncalls.patch) for some boxes  * other:   * Config.in:    * Add libtr064 to remove tr069 help text    * Fix AVM-Plugin selection for 7270 16 MB    * reactivate remove of smbd and mediasrv for 7240 and 7270_V3, because these are no plugins    * correct some unnecessary dependencies for W701V Alien   * fwmod:    * add FAQ-URL for 'image too big' error    * dynamicly creation of /usr/bin/system_status with all applyed patches and packages    * edit libssl/libcrypto-hint    * Fix error that Addon Files were not copied to var.tar correctly   * "make config-clean-deps": Look at FREETZ_SHARE symbols also   * updated .build-prerequisites with all necessary programs   * Update device tables, add new device kdsld_multid
git-svn-id: http://svn.freetz.org/branches/freetz-stable-1.1@3557 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/patches/cond/usbstorage_7270_labor_dsl.patch b/patches/cond/usbstorage_7270_labor_dsl.patch
--- a/patches/cond/usbstorage_7270_labor_dsl.patch
+++ b/patches/cond/usbstorage_7270_labor_dsl.patch
@@ -1,42 +1,33 @@
---- etc/hotplug/run_mount.orig	2008-05-24 14:38:58.000000000 +0200
-+++ etc/hotplug/run_mount	2008-05-24 14:42:31.000000000 +0200
-@@ -36,31 +36,8 @@
- # Generate a frontend'able 'nice name' to be used as mount point:
- #
- nicename () {
--	local PROD
--	local SNUM
--	local MANU
--	local NAME="USB"
- 	local NICE=""
--
--	# Find device's strings, remove/translate evil chars...
--	for VAR in `/sbin/lsusb -s -h $1|tr -d ' '`; do
--		if echo $VAR | grep "='" > /dev/null 2>&1; then
--			eval "${VAR%%=*}=`echo ${VAR##*=}|tr -c "\n\'a-zA-Z0-9" '-' | tr -d \' `"
--		fi
--	done
--	
--	# Find a string for our new nice name...
--	if ! test -z "$PROD"; then
--		NAME="$PROD"
--	elif ! test -z "$MANU"; then
--		NAME="$MANU"
--	fi
--	if ! test -z "$NAME"; then
--		NAME=`echo $NAME|tr ':' ' '`
--	fi
--	
--	# Build nice name: [Product/Vendor name]-Partition-<x>-<y>
--	NICE="$NAME-Partition-$2-$3"
-+	NICE="uStor`echo $1|sed 's/^..//;s/a/0/;s/b/1/;s/c/2/;s/d/3/;s/e/4/;s/f/5/;s/g/6/;s/h/7/;s/i/8/;s/j/9/'`$3"
- 	echo $NICE
- }
+--- etc/hotplug/run_mount.orig	2009-08-08 11:09:55.745976194 +0200
++++ etc/hotplug/run_mount	2009-08-08 11:09:56.545482874 +0200
+@@ -22,19 +22,9 @@
  
-@@ -74,6 +51,36 @@
+ ## Generate a frontend'able 'nice name' to be used as mount point:
+ nicename () {
+-## Find device's strings, remove/translate evil chars...
+-local MANU=`cat $SYSFS/block/$1/device/vendor|tr -d ' '|tr -c "\na-zA-Z0-9" '-'`
+-local NAME=`cat $SYSFS/block/$1/device/model|tr -d ' '|tr -c "\na-zA-Z0-9" '-'`
+-local PARTHEX=$3
+-if [ $PARTHEX -gt 9 ]; then
+-PARTHEX=`echo $((PARTHEX-10)) | tr "0-5" "A-F"`
+-fi
+-test -z "$NAME" && NAME="Storage"
+-test -n "$MANU" && NAME="$MANU-$NAME"
+-## limit NAME to 30 characters+3 extra characters (-00)
+-NAME=`echo -n "$NAME" | sed -e 's#\(.\{0,30\}\).*#\1#g'`
+-## Build nice name: [Vendor-Product]-<x><y>
+-echo "$NAME-$2$PARTHEX"
++local NICE=""
++NICE="uStor`echo $1|sed 's/^..//;s/a/0/;s/b/1/;s/c/2/;s/d/3/;s/e/4/;s/f/5/;s/g/6/;s/h/7/;s/i/8/;s/j/9/'`$3"
++echo $NICE
+ }
+ ## Simple semaphore stuff:
+ ## includes /etc/hotplug/rc.usbsema
+@@ -45,6 +35,37 @@
+ ## atomic_touch (Filename)
  USBLOCKFILE=/var/USBLOCK_storage
  test -f /etc/hotplug/rc.usbsema && . /etc/hotplug/rc.usbsema
- 
++
 +mount_fs () {
 + # mount according to type of filesystem 
 + # return exit code: true - all went well; other - something went wrong 
@@ -56,7 +47,7 @@
 +		mount -t ext3 $DEVNODE $MNTPATH -o noatime,nodiratime,rw,async
 +		;;
 +	ntfs)
-+		/usr/bin/ntfs-3g $DEVNODE $MNTPATH -o force
++		/usr/bin/ntfs-3g $DEVNODE $MNTPATH -o $READMODE -o force -o locale=de_DE.ISO-8859-1
 +		;;
 +	reiserfs)
 +		mount -t reiserfs $DEVNODE $MNTPATH -o noatime,nodiratime,rw,async
@@ -67,42 +58,57 @@
 +	esac
 +}
 +
- # Actually perform the mount operation...
- # (TODO Checking the partition for known filesystem types)
- #
-@@ -100,34 +106,8 @@
-         local OLD_UMASK=`umask`
- 	umask 0
- 	local new_filesystem=false
--	if mount -t vfat -o $READMODE,uid=$FTPUID,gid=$FTPGID $DEVNODE $MNTPATH; then
--		new_filesystem=true
--	else
--		if test -x /bin/ntfs-3g ; then
--			ntfs-3g $DEVNODE $MNTPATH -o $READMODE
--			local NTFS_RET=$?
--			case "$NTFS_RET" in
--			0 )
-+	if mount_fs; then
- 				new_filesystem=true
--				;;
--
--			12 )	# NTFS_VOLUME_NOT_NTFS
--				# ignore - not formatted with NTFS
--				;;
--			16 )    # NTFS_VOLUME_UNCLEAN_UNMOUNT
--				# need option -o force, but we don't do this, because its not safe!
--				eventadd 144 $MNTNAME
--				# no fail event later on
--				FAIL_EVENT=0
--				;;
--			* )
--				# NTFS mount error
--				eventadd 145 $MNTNAME $NTFS_RET
--				# no fail event later on
--				FAIL_EVENT=0
--				;;
--			esac
--		fi
- 	fi
- 	if [ $new_filesystem = true ] ; then
- 		umask $OLD_UMASK
+ ## Actually perform the mount operation...
+ ## (TODO Checking the partition for known filesystem types)
+ do_mount () {
+@@ -79,41 +100,7 @@
+ ## run mount with umask 0 so everyone is allowed to rwx everywhere
+ local OLD_UMASK=`umask`
+ umask 0
+-local new_filesystem=false
+-if mount -t vfat -o $READMODE,shortname=winnt,uid=$FTPUID,gid=$FTPGID $DEVNODE $MNTPATH; then
+-new_filesystem=true
+-else
+-if test -x /bin/ntfs-3g ; then
+-ntfs-3g $DEVNODE $MNTPATH -o $READMODE -o locale=de_DE.ISO-8859-1
+-local NTFS_RET=$?
+-case "$NTFS_RET" in
+-0 )
+-new_filesystem=true
+-;;
+-12 ) # NTFS_VOLUME_NOT_NTFS
+-## ignore - not formatted with NTFS
+-;;
+-15 ) # NTFS_VOLUME_UNCLEAN_UNMOUNT
+-## need option -o force, but we don't do this, because its not safe!
+-eventadd 144 $MNTNAME
+-## no fail event later on
+-FAIL_EVENT=0
+-led-ctrl filesystem_mount_failure
+-;;
+-* )
+-## NTFS mount error
+-eventadd 145 $MNTNAME $NTFS_RET
+-## no fail event later on
+-FAIL_EVENT=0
+-led-ctrl filesystem_mount_failure
+-;;
+-esac
+-else
+-echo "ntfs not yet ready -> mount later" > /dev/ttyS0
+-FAIL_EVENT=0
+-fi
+-fi
+-if [ $new_filesystem = true ] ; then
++if mount_fs; then
+ FAIL_EVENT=0
+ umask $OLD_UMASK
+ eventadd 140 $MNTNAME
+@@ -155,6 +142,7 @@
+ else
+ umask $OLD_UMASK
+ rmdir $MNTPATH
++eventadd 142 $MNTNAME NOTMOUNTABLE
+ fi
+ if grep $MNTPATH /proc/mounts > /dev/null; then
+ if test -f $1; then
