[freetz-stable-1.1]: tcpdump: fix compile error (backported from trunk), see http://www.ip-phone-forum.de/showthread.php?t=216796
git-svn-id: http://svn.freetz.org/branches/freetz-stable-1.1@5084 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/make/tcpdump/patches/02-shared_pcap.patch b/make/tcpdump/patches/02-shared_pcap.patch
--- a/make/tcpdump/patches/02-shared_pcap.patch
+++ b/make/tcpdump/patches/02-shared_pcap.patch
@@ -1,43 +1,70 @@
---- aclocal.m4.orig	2008-01-23 12:03:50.000000000 +0100
-+++ aclocal.m4	2008-01-23 12:04:24.000000000 +0100
-@@ -237,21 +237,6 @@
-     AC_MSG_CHECKING(for local pcap library)
-     libpcap=FAIL
-     lastdir=FAIL
+--- configure	2007-09-25 19:16:50.000000000 -0700
++++ configure	2009-05-21 17:17:07.000000000 -0700
+@@ -9278,26 +9278,6 @@
+ 		    LIBS="$LIBS $pfopen"
+ 	    fi
+     fi
+-    { echo "$as_me:$LINENO: checking for local pcap library" >&5
+-echo $ECHO_N "checking for local pcap library... $ECHO_C" >&6; }
+-    libpcap=FAIL
+-    lastdir=FAIL
 -    places=`ls $srcdir/.. | sed -e 's,/$,,' -e "s,^,$srcdir/../," | \
--	egrep '/libpcap-[[0-9]]*.[[0-9]]*(.[[0-9]]*)?([[ab]][[0-9]]*)?$'`
+-	egrep '/libpcap-[0-9]*.[0-9]*(.[0-9]*)?([ab][0-9]*)?$'`
 -    for dir in $places $srcdir/../libpcap $srcdir/libpcap ; do
--	    basedir=`echo $dir | sed -e 's/[[ab]][[0-9]]*$//'`
+-	    basedir=`echo $dir | sed -e 's/[ab][0-9]*$//'`
 -	    if test $lastdir = $basedir ; then
--		    dnl skip alphas when an actual release is present
--		    continue;
+-		    		    continue;
 -	    fi
 -	    lastdir=$dir
 -	    if test -r $dir/libpcap.a ; then
 -		    libpcap=$dir/libpcap.a
 -		    d=$dir
--		    dnl continue and select the last one that exists
--	    fi
+-		    	    fi
 -    done
-     if test $libpcap = FAIL ; then
- 	    AC_MSG_RESULT(not found)
- 	    AC_CHECK_LIB(pcap, main, libpcap="-lpcap")
-@@ -288,18 +273,6 @@
- 		$2="-I$d $$2"
- 		AC_MSG_RESULT(found -- -I$d added)
+-    if test $libpcap = FAIL ; then
+-	    { echo "$as_me:$LINENO: result: not found" >&5
+-echo "${ECHO_T}not found" >&6; }
+ 	    { echo "$as_me:$LINENO: checking for main in -lpcap" >&5
+ echo $ECHO_N "checking for main in -lpcap... $ECHO_C" >&6; }
+ if test "${ac_cv_lib_pcap_main+set}" = set; then
+@@ -9362,40 +9342,6 @@
+ echo "$as_me: error: see the INSTALL doc for more info" >&2;}
+    { (exit 1); exit 1; }; }
  	    fi
--    else
--	    $1=$libpcap
--	    places=`ls $srcdir/.. | sed -e 's,/$,,' -e "s,^,$srcdir/../," | \
--    	 		egrep '/libpcap-[[0-9]]*.[[0-9]]*(.[[0-9]]*)?([[ab]][[0-9]]*)?$'`
--	    if test -r $d/pcap.h; then
--		    $2="-I$d $$2"
--	    elif test -r $places/pcap.h; then
--		    $2="-I$places $$2"
+-	    	    	    	    	    	    	    	    	    	    	    	    	    	    	    	    { echo "$as_me:$LINENO: checking for extraneous pcap header directories" >&5
+-echo $ECHO_N "checking for extraneous pcap header directories... $ECHO_C" >&6; }
+-	    if test \( ! -r /usr/local/include/pcap.h \) -a \
+-			\( ! -r /usr/include/pcap.h \); then
+-		if test -r /usr/local/include/pcap/pcap.h; then
+-		    d="/usr/local/include/pcap"
+-		elif test -r /usr/include/pcap/pcap.h; then
+-		    d="/usr/include/pcap"
+-		fi
+-	    fi
+-	    if test -z "$d" ; then
+-		{ echo "$as_me:$LINENO: result: not found" >&5
+-echo "${ECHO_T}not found" >&6; }
 -	    else
--                    AC_MSG_ERROR(cannot find pcap.h, see INSTALL)
+-		V_INCLS="-I$d $V_INCLS"
+-		{ echo "$as_me:$LINENO: result: found -- -I$d added" >&5
+-echo "${ECHO_T}found -- -I$d added" >&6; }
+-	    fi
+-    else
+-	    V_PCAPDEP=$libpcap
+-	    places=`ls $srcdir/.. | sed -e 's,/$,,' -e "s,^,$srcdir/../," | \
+-    	 		egrep '/libpcap-[0-9]*.[0-9]*(.[0-9]*)?([ab][0-9]*)?$'`
+-	    if test -r $d/pcap.h; then
+-		    V_INCLS="-I$d $V_INCLS"
+-	    elif test -r $places/pcap.h; then
+-		    V_INCLS="-I$places $V_INCLS"
+-	    else
+-                    { { echo "$as_me:$LINENO: error: cannot find pcap.h" >&5
+-echo "$as_me: error: cannot find pcap.h" >&2;}
+-   { (exit see INSTALL); exit see INSTALL; }; }
 - 	    fi
--	    AC_MSG_RESULT($libpcap)
-     fi
+-	    { echo "$as_me:$LINENO: result: $libpcap" >&5
+-echo "${ECHO_T}$libpcap" >&6; }
+-    fi
      LIBS="$libpcap $LIBS"
      case "$host_os" in
+ 
