* Remove usage of modlibrc from scripts that aren't rc-scripts   * doesn't work because $1 is not in "", start, ...
git-svn-id: http://svn.freetz.org/trunk@5033 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/make/hp-utils/files/root/usr/bin/webcfg-hp-utils b/make/hp-utils/files/root/usr/bin/webcfg-hp-utils
--- a/make/hp-utils/files/root/usr/bin/webcfg-hp-utils
+++ b/make/hp-utils/files/root/usr/bin/webcfg-hp-utils
@@ -1,8 +1,16 @@
 #!/bin/sh
 
+export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/mod/sbin:/mod/bin:/mod/usr/sbin:/mod/usr/bin
+export LD_LIBRARY_PATH=/mod/lib
+
 DAEMON=hp-utils
 
-. /etc/init.d/modlibrc
+if [ ! -r "/mod/etc/conf/hp-utils.cfg" ]; then
+	echo "Error[$DAEMON]: not configured" 1>&2
+	exit 1
+fi
+
+. /mod/etc/conf/hp-utils.cfg
 
 homedir=/mod/pkg/hp-utils/usr/mww-hp-utils/
 
diff --git a/make/rrdstats/files/root/usr/bin/webcfg-rrd b/make/rrdstats/files/root/usr/bin/webcfg-rrd
--- a/make/rrdstats/files/root/usr/bin/webcfg-rrd
+++ b/make/rrdstats/files/root/usr/bin/webcfg-rrd
@@ -1,14 +1,22 @@
 #!/bin/sh
 
-DAEMON=rrdstats
-. /etc/init.d/modlibrc
+export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/mod/sbin:/mod/bin:/mod/usr/sbin:/mod/usr/bin
+export LD_LIBRARY_PATH=/mod/lib
 
+DAEMON=rrdstats
 SUBDAEMON=rrd
+
+if [ ! -r "/mod/etc/conf/rrdstats.cfg" ]; then
+	echo "Error[$DAEMON]: not configured" 1>&2
+	exit 1
+fi
+
 . /mod/etc/conf/rrdstats.cfg
+
 homedir=/mod/pkg/rrdstats/usr/mww-$SUBDAEMON/
 
 if [ "$RRDSTATS_WEB_AUTH" = yes ]; then
-	echo "/:$RRDSTATS_WEB_USER:$(httpd -m $RRDSTATS_WEB_PASS)" >/mod/etc/httpd-$SUBDAEMON.conf
+	echo "/:$RRDSTATS_WEB_USER:$(httpd -m $RRDSTATS_WEB_PASS)" > /mod/etc/httpd-$SUBDAEMON.conf
 	RRD_CONF="-c /mod/etc/httpd-$SUBDAEMON.conf"
 fi
 
diff --git a/make/wol-cgi/files/root/usr/bin/webcfg-wol b/make/wol-cgi/files/root/usr/bin/webcfg-wol
--- a/make/wol-cgi/files/root/usr/bin/webcfg-wol
+++ b/make/wol-cgi/files/root/usr/bin/webcfg-wol
@@ -1,9 +1,17 @@
 #!/bin/sh
 
-DAEMON=wol
-. /etc/init.d/modlibrc
-. /mod/etc/conf/$DAEMON.cfg
+export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/mod/sbin:/mod/bin:/mod/usr/sbin:/mod/usr/bin
+export LD_LIBRARY_PATH=/mod/lib
+
+DAEMON=httpd-wol
+
+if [ ! -r "/mod/etc/conf/wol.cfg" ]; then
+	echo "Error[$DAEMON]: not configured" 1>&2
+	exit 1
+fi
+
+. /mod/etc/conf/wol.cfg
 
 homedir=/mod/pkg/wol/usr/mww-wol/
 
-exec httpd "$@" -p "$WOL_PORT" -c /mod/etc/httpd-$DAEMON.conf -h "$homedir" -r "Wake-on-LAN"
+exec httpd "$@" -p "$WOL_PORT" -c /mod/etc/$DAEMON.conf -h "$homedir" -r "Wake-on-LAN"
