modlibrc: check if file is executable (and exists)
git-svn-id: http://svn.freetz.org/trunk@6918 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/make/mod/files/root/etc/init.d/modlibrc b/make/mod/files/root/etc/init.d/modlibrc
--- a/make/mod/files/root/etc/init.d/modlibrc
+++ b/make/mod/files/root/etc/init.d/modlibrc
@@ -141,6 +141,11 @@ modlib_startdaemon() {
 	echo -n "Starting ${DAEMON_LONG_NAME} ... "
 	config
 
+	if [ ! -x "$(which $1)" ]; then
+		echo "could not execute $1, failed."
+		exit 1
+	fi
+
 	env - PATH="$PATH" $DAEMON_ENV "$@" 1>&2
 	local rv=$?
 
