modlibrc: fix punctuation to show colors in webif
git-svn-id: http://svn.freetz.org/trunk@5998 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/make/mod/files/root/etc/init.d/modlibrc b/make/mod/files/root/etc/init.d/modlibrc
--- a/make/mod/files/root/etc/init.d/modlibrc
+++ b/make/mod/files/root/etc/init.d/modlibrc
@@ -58,7 +58,7 @@ modlib_addgroup() {
 	echo -n "Looking for group '$group' ... "
 	if addgroup "$@" "$group"; then
 		echo -n "created - now saving to data buffer ... "
-		modusers save && echo "done" || echo "failed"
+		modusers save && echo "done." || echo "failed."
 	else
 		echo "not created - error occurred"
 	fi
@@ -79,7 +79,7 @@ modlib_adduser() {
 	local msg=$(adduser "$@" "$user" 2>&1)
 	if [ $? -eq 0 ]; then
 		echo -n "created - now saving to data buffer ... "
-		modusers save && echo "done" || echo "failed"
+		modusers save && echo "done." || echo "failed."
 	else
 		echo "not created - error occurred: $msg"
 		exit 1
