color "not configured" output of modlibrc (refs #897)
git-svn-id: http://svn.freetz.org/trunk@6196 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/make/mod/files/root/etc/init.d/modlibrc b/make/mod/files/root/etc/init.d/modlibrc
--- a/make/mod/files/root/etc/init.d/modlibrc
+++ b/make/mod/files/root/etc/init.d/modlibrc
@@ -370,7 +370,7 @@ modlib_status() {
 modlib_loadconfig() {
 	local CONF_FILE="/mod/etc/conf/${1-$CONF_NAME}.cfg"
 	if [ ! -r "$CONF_FILE" ]; then
-		echo "Error[${DAEMON_LONG_NAME}]: not configured" 1>&2
+		echo "Error [${DAEMON_LONG_NAME}]: not configured." 1>&2
 		exit 1
 	fi
 	. "$CONF_FILE"
