modlibrc: add modlib_add_user_and_group (refs #1152)
git-svn-id: http://svn.freetz.org/trunk@9759 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/make/mod/files/root/etc/init.d/modlibrc b/make/mod/files/root/etc/init.d/modlibrc
--- a/make/mod/files/root/etc/init.d/modlibrc
+++ b/make/mod/files/root/etc/init.d/modlibrc
@@ -50,45 +50,54 @@ stop_post() { :; }
 
 
 # modlib_addgroup:
-#   check for group name, create group if not found.
+#   check for group and create it if not found.
 #   No check is done for a change in the optional arguments!
 #	$1: group name
 #	$2-n: optional arguments for addgroup
 modlib_addgroup() {
 	local group=$1
 	shift
-	if grep -q "^$group:" /etc/group; then
-		return 0
-	fi
-	echo -n "Looking for group '$group' ... "
-	if addgroup "$@" "$group"; then
-		echo -n "created - now saving to data buffer ... "
+	grep -q "^$group:" /etc/group && return 0
+	echo -n "Creating group '$group' ... "
+	local msg=$(addgroup $@ $group 2>&1)
+	if [ $? -eq 0 ]; then
+		echo -n "saving ... "
 		modusers save && echo "done." || echo "failed."
 	else
-		echo "not created - error occurred"
+		echo "failed: $msg"
+		exit 1
 	fi
 }
 
 # modlib_adduser:
-#   check for user name, create user if not found.
+#   check for user and create it if not found.
 #   No check is done for a change in the optional arguments!
 #	$1: user name
 #	$2-n: optional arguments for adduser
 modlib_adduser() {
 	local user=$1
 	shift
-	if grep -q "^$user:" /etc/passwd; then
-		return 0
-	fi
-	echo -n "Looking for user '$user' ... "
-	local msg=$(adduser "$@" "$user" 2>&1)
+	grep -q "^$user:" /etc/passwd && return 0
+	echo -n "Creating user '$user' ... "
+	local msg="$(adduser $@ $user 2>&1)"
 	if [ $? -eq 0 ]; then
-		echo -n "created - now saving to data buffer ... "
+		echo -n "saving ... "
 		modusers save && echo "done." || echo "failed."
 	else
-		echo "not created - error occurred: $msg"
+		echo "failed: $msg"
 		exit 1
 	fi
+}
+
+# modlib_add_user_and_group:
+#   check for user & group and create them if not found.
+#	$1: user name
+#	$2: group name (optional)
+modlib_add_user_and_group() {
+	local user=$1
+	[ $# -gt 1 ] && local group=$2 || local group=$1
+	modlib_addgroup $group
+ 	modlib_adduser $user -s /bin/false -D -S -H -G $group -g "$user"
 }
 
 # modlib_check_running
