revert passwd changes

diff --git a/make/mod/files/root/etc/init.d/modlibrc b/make/mod/files/root/etc/init.d/modlibrc
--- a/make/mod/files/root/etc/init.d/modlibrc
+++ b/make/mod/files/root/etc/init.d/modlibrc
@@ -100,13 +100,10 @@ modlib_adduser() {
 	shift
 	grep -q "^$user:" /etc/passwd && return 0
 	echo -n "Creating user '$user' ... "
-	local msg="$(modadduser $@ $user 2>&1)"
-	local ret=$?
-#	if [ $ret -eq 0 ]; then
-#		echo -n "saving ... "
-#		modusers save && echo "done." || echo "failed."
-#	else
-	if [ $ret -ne 0 ]; then
+	local msg="$(adduser $@ $user 2>&1)"
+	if [ $? -eq 0 ]; then
+		modusers save && echo "done." || echo "failed."
+	else
 		echo "failed: $msg"
 		exit 1
 	fi
