* fwmod: fix utf-8 problem  * fwmod: hopefully last occurence of error-function before included functions and .config are present
git-svn-id: http://svn.freetz.org/trunk@3596 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/fwmod b/fwmod
--- a/fwmod
+++ b/fwmod
@@ -27,7 +27,7 @@
 # This script is based on Christian Volkmann's fritzbox mod-0.57.
 # Legacy URL: http://www.ip-phone-forum.de/showthread.php?t=65894
 #
-# Special Thanks to Andreas Bühmann, Christian Volkmann, Enrik Berkhan,
+# Special Thanks to Andreas Buehmann, Christian Volkmann, Enrik Berkhan,
 # SpeedyBZ and all members on ip-phone-forum.de who contributed to this mod
 
 SHELL=$BASH
@@ -200,7 +200,8 @@ DYNAMIC_ADDON_FILE="${ADDON_DIR}/dynamic.pkg"
 
 # Config file readable?
 if [ ! -r "$DOT_CONFIG" ]; then
-	error 1 "not configured"
+	echo -e "ERROR: not configured" 1>&2
+	exit 1
 fi
 
 # Load config
