fwmod:  * adjust indentation (no functional changes)
git-svn-id: http://svn.freetz.org/trunk@13399 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/fwmod b/fwmod
--- a/fwmod
+++ b/fwmod
@@ -1615,17 +1615,17 @@ if [ "$DO_PACK" -gt 0 ]; then
 
 	if [ "${FREETZ_AVM_HAS_UPDATE_FILESYSTEM_IMAGE}" == "y" ]; then
 
-if [ "${FREETZ_AVM_HAS_EXT2_SQUASHFS4_PACKAGING_SCHEME}" == "y" ]; then
-		PATH="$TOOLS_DIR:$PATH" $TOOLS_DIR/mke2img -G 2 -R 0 -d "$FILESYSTEM_CORE_MOD_DIR" -o "$ABS_BASE_DIR/$RAW_FILESYSTEM_MOD.ext2" >> $MOD_DIR/filesystem.log 2>&1
-		[ $? -ne 0 -o ! -s "$RAW_FILESYSTEM_MOD.ext2" ] && error 1 "creation of ext2 image failed"
+		if [ "${FREETZ_AVM_HAS_EXT2_SQUASHFS4_PACKAGING_SCHEME}" == "y" ]; then
+			PATH="$TOOLS_DIR:$PATH" $TOOLS_DIR/mke2img -G 2 -R 0 -d "$FILESYSTEM_CORE_MOD_DIR" -o "$ABS_BASE_DIR/$RAW_FILESYSTEM_MOD.ext2" >> $MOD_DIR/filesystem.log 2>&1
+			[ $? -ne 0 -o ! -s "$RAW_FILESYSTEM_MOD.ext2" ] && error 1 "creation of ext2 image failed"
 
-		# TODO: AVM uses a header which looks like a SquashFS header, we use a "zeros only"-header, check if it's OK, i.e. if AVM verifies these 256 bytes somewhere
-		dd if=/dev/zero of="$RAW_FILESYSTEM_MOD" bs=1 count=0 seek=256 >> $MOD_DIR/filesystem.log 2>&1 && \
-		cat "$RAW_FILESYSTEM_MOD.ext2" >> "$RAW_FILESYSTEM_MOD" && \
-		rm -f "$RAW_FILESYSTEM_MOD.ext2"
-else
-		"$MKSQUASHFS" $FILESYSTEM_CORE_MOD_DIR/* $ABS_BASE_DIR/$RAW_FILESYSTEM_MOD $MKSQUASHFS_OPTIONS >> $MOD_DIR/filesystem.log 2>&1
-fi
+			# TODO: AVM uses a header which looks like a SquashFS header, we use a "zeros only"-header, check if it's OK, i.e. if AVM verifies these 256 bytes somewhere
+			dd if=/dev/zero of="$RAW_FILESYSTEM_MOD" bs=1 count=0 seek=256 >> $MOD_DIR/filesystem.log 2>&1 && \
+			cat "$RAW_FILESYSTEM_MOD.ext2" >> "$RAW_FILESYSTEM_MOD" && \
+			rm -f "$RAW_FILESYSTEM_MOD.ext2"
+		else
+			"$MKSQUASHFS" $FILESYSTEM_CORE_MOD_DIR/* $ABS_BASE_DIR/$RAW_FILESYSTEM_MOD $MKSQUASHFS_OPTIONS >> $MOD_DIR/filesystem.log 2>&1
+		fi
 
 		[ ! -s "$RAW_FILESYSTEM_MOD" ] && error 1 "creation of filesystem failed"
 		let FILESYSTEM_SIZE="$(wc -c < "$RAW_FILESYSTEM_MOD")"
