fix tagging for non-firefox

diff --git a/fwmod b/fwmod
--- a/fwmod
+++ b/fwmod
@@ -1427,38 +1427,36 @@ if [ "$DO_MOD" -gt 0 ]; then
 			tagging() {
 				[ $# -lt 3 ] && return
 				local tagging_geo="$1"
-				shift
-				local tagging_pos="$1"
-				shift
-				local tagging_arg="$*"
-				local tagging_pic="${TAGGING_DIR}/${FREETZ_TAGGING_STRING}.png"
-				for tagging_file in $tagging_arg; do
-					echo2 "${tagging_file}"
-					[ "${tagging_file}" != "${tagging_file%\.svg}" ] && tagging_temp="${tagging_file}.png" || tagging_temp=""
-					[ -n "$tagging_temp" ] && convert -compress NONE -background NONE -resize 100x80 "$tagging_file" "$tagging_temp"
-					composite -dissolve 100% -gravity $tagging_pos -geometry $tagging_geo -quality 100 $tagging_pic ${tagging_temp:-$tagging_file} ${tagging_temp:-$tagging_file}
-					[ $? -ne 0 ] && error 1 "tagging failed while processing ${tagging_file#${FILESYSTEM_MOD_DIR}/}"
-					[ -n "$tagging_temp" ] && mv "$tagging_temp" "$tagging_file"  #BETTER: "convert" to svg (and delete)
+				local tagging_pos="$2"
+				local tagging_arg="$3"
+				for d in ${HTML_MOD_DIR}*; do
+					[ ! -d "$d" ] && continue
+					local tagging_ren=""
+					for tagging_file in $(find "$d" -name "$tagging_arg"); do
+						echo2 "${tagging_file}"
+						[ "${tagging_file}" != "${tagging_file%svg}" ] && tagging_temp="${tagging_file%svg}png" || tagging_temp=""
+						[ -n "$tagging_temp" ] && convert -compress NONE -background NONE -resize 100x80 "$tagging_file" "$tagging_temp"
+						composite -dissolve 100% -gravity $tagging_pos -geometry $tagging_geo -quality 100 \
+						  "${TAGGING_DIR}/${FREETZ_TAGGING_STRING}.png" ${tagging_temp:-$tagging_file} ${tagging_temp:-$tagging_file}
+						[ $? -ne 0 ] && error 1 "tagging failed while processing ${tagging_file#${FILESYSTEM_MOD_DIR}/}"
+						[ -n "$tagging_temp" ] && tagging_ren="$tagging_ren ${tagging_file##*/}" && rm -f "${tagging_file}"
+					done
+					[ -z "$tagging_temp" ] && continue
+					for i in $(echo "$tagging_ren" | sed 's, ,\n,g' | sort -u); do
+						for j in $(grep -l "$i" "$d" -r); do
+							sed "s,${i},${i%svg}png,g" -i "$j"
+						done
+					done
 				done
 			}
 			echo1 "tagging avm webif (tag by ${FREETZ_TAGGING_STRING})"
-			for d in "${HTML_MOD_DIR}" "${HTML_MOD_DIR}.nas"; do
-				[ -d "${d}" ] || continue
-				# svg since Fritz!OS 07.1x
-				tagging "+0+6" "center" $(find "${d}" -name logo_fritzDiamond.svg)
-				# svg since Fritz!OS 06.5x (eg 7320 06.50)
-				tagging "+0+6" "center" $(find "${d}" -name fritzLogo.svg)
-				# lua since  Fritz!OS 6.2x (small logo @left, eg 7390 06.23)
-				tagging "+0+6" "center" $(find "${d}" -name kopfbalken_links.png)
-				# lua before Fritz!OS 6.2x (small logo @left, eg 7270 04.88)
-				tagging "+0+0" "center" $(find "${d}" -name kopfbalken_links.gif)
-				# newer html (big header @top, eg 7320 05.29)
-				tagging "-20+0" "west" $(find "${d}" -name kopfbalken.gif)
-				# older (big header @top, eg 7141 04.76)
-				tagging "+0+0" "west" $(find "${d}" -name fw_header980.gif)
-				# even older (big header @top, eg 7050 04.03)
-				tagging "+0-5" "west" $(find "${d}" -name fw_header.gif)
-			done
+			tagging  "+0+6" "center" logo_fritzDiamond.svg    # svg since  Fritz!OS 7.1x (eg 7490 07.11)
+			tagging  "+0+6" "center" fritzLogo.svg            # svg since  Fritz!OS 6.5x (eg 7320 06.50)
+			tagging  "+0+6" "center" kopfbalken_links.png     # lua since  Fritz!OS 6.2x (small logo @left, eg 7390 06.23)
+			tagging  "+0+0" "center" kopfbalken_links.gif     # lua before Fritz!OS 6.2x (small logo @left, eg 7270 04.88)
+			tagging "-20+0" "west"   kopfbalken.gif           # newer html (big header @top, eg 7320 05.29)
+			tagging  "+0+0" "west"   fw_header980.gif         # older (big header @top, eg 7141 04.76)
+			tagging  "+0-5" "west"   fw_header.gif            # even older (big header @top, eg 7050 04.03)
 		fi
 
 	fi
