* treat filesystem image decompression errors as fatal, this way we would notice errors like those from #2690 much earlier  * refs #2690
Note: you need to run {{{make squashfs2-distclean squashfs3-distclean}}} after updating to this revision in order to force the rebuild of squashfs-tools


git-svn-id: http://svn.freetz.org/trunk@12960 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/fwmod b/fwmod
--- a/fwmod
+++ b/fwmod
@@ -449,7 +449,7 @@ if [ "$DO_UNPACK" -gt 0 ]; then
 		[ ! -r "$RAW_KERNEL" -o ! -r "$FILESYSTEM" ] && error 1 "copying kernel or filesystem image failed"
 
 		echo "unpacking filesystem image"
-		modunsqfs "$FILESYSTEM_DIR" "$FILESYSTEM"
+		modunsqfs "$FILESYSTEM_DIR" "$FILESYSTEM" || error 1 "unpacking filesystem image failed"
 	else
 		echo "splitting kernel image"
 		( cd "$KERNEL_DIR" && "${TOOLS_DIR}/${FINDSQUASHFS_TOOL}" "../${FIRMWARE_SUBDIR}/${KERNEL_IMAGE}" > /dev/null 2>&1 )
@@ -462,7 +462,7 @@ if [ "$DO_UNPACK" -gt 0 ]; then
 		fi
 
 		echo "unpacking filesystem image"
-		modunsqfs_lzma "$FILESYSTEM_DIR" "$FILESYSTEM"
+		modunsqfs_lzma "$FILESYSTEM_DIR" "$FILESYSTEM" || error 1 "unpacking filesystem image failed"
 	fi
 
 	if [ -r "$AVMPLUGINS" ]; then
