* FREETZ_TYPE_PREFIX: no _labor postfix needed anymore, will be appended automatically  * one patch directory for firmware series
git-svn-id: http://svn.freetz.org/trunk@9775 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/fwmod b/fwmod
--- a/fwmod
+++ b/fwmod
@@ -639,19 +639,25 @@ if [ "$DO_MOD" -gt 0 ]; then
 	# Include patching helper function (modpatch)
 	. "${TOOLS_DIR}/freetz_patch" || error 1 "cannot find script freetz_patch"
 
-	echo1 "applying patches (${FREETZ_TYPE_PREFIX}-${FREETZ_TYPE_LANGUAGE})"
+	PATCHES_DEVICES_DIR_EXTRA="${PATCHES_DEVICES_DIR}/${FREETZ_TYPE_PREFIX}${FREETZ_TYPE_PREFIX_LABOR_FIRMWARE}"
+	if [ -n "$FREETZ_AVM_VERSION_SERIES" ]; then
+		PATCHES_DEVICES_DIR_MULTI="${PATCHES_DEVICES_DIR}/0000-${FREETZ_AVM_VERSION_SERIES}"
+	fi
+
+	echo1 "applying patches: ${FREETZ_TYPE_PREFIX}${FREETZ_TYPE_PREFIX_LABOR_FIRMWARE}-${FREETZ_TYPE_LANGUAGE} ${PATCHES_DEVICES_DIR_MULTI##*/}"
 
 	# Apply patches
-	if [ ! -d "${PATCHES_DEVICES_DIR}/${FREETZ_TYPE_PREFIX}" ]; then
-		error 1 "missing ${PATCHES_DEVICES_DIR}/${FREETZ_TYPE_PREFIX}"
+	if [ ! -d "$PATCHES_DEVICES_DIR_EXTRA" -a ! -d "$PATCHES_DEVICES_DIR_MULTI" ]; then
+		error 1 "missing $PATCHES_DEVICES_DIR_EXTRA"
 	fi
 
 	# Execute version specific patch scripts
-	for i in "${PATCHES_DEVICES_DIR}/${FREETZ_TYPE_PREFIX}/${FREETZ_TYPE_LANGUAGE}/"*.sh \
-		"${PATCHES_DEVICES_DIR}/${FREETZ_TYPE_PREFIX}/"*.sh; do
-		[ -r "$i" ] || continue
-		echo2 "applying patch file $i"
-		. $i
+	for j in ${PATCHES_DIR} $PATCHES_DEVICES_DIR_MULTI $PATCHES_DEVICES_DIR_EXTRA; do
+		for i in $j/*.sh $j/${FREETZ_TYPE_LANGUAGE}/*.sh; do
+			[ -r "$i" ] || continue
+			echo2 "applying patch file $i"
+			. $i
+		done
 	done
 
 	# Now we are in place to check html directory
@@ -666,11 +672,10 @@ if [ "$DO_MOD" -gt 0 ]; then
 
 	# Apply (general, version specific, language specific) patches
 	shopt -s nullglob
-	for i in "${PATCHES_DIR}/"*.patch \
-		"${PATCHES_DEVICES_DIR}/${FREETZ_TYPE_PREFIX}/"*.patch \
-		"${PATCHES_DEVICES_DIR}/${FREETZ_TYPE_PREFIX}/${FREETZ_TYPE_LANGUAGE}/"*.patch
-	do
-		modpatch "$FILESYSTEM_MOD_DIR" "$i"
+	for j in ${PATCHES_DIR} $PATCHES_DEVICES_DIR_MULTI $PATCHES_DEVICES_DIR_EXTRA; do
+		for i in $j/*.patch $j/${FREETZ_TYPE_LANGUAGE}/*.patch; do
+			modpatch "$FILESYSTEM_MOD_DIR" "$i"
+		done
 	done
 	shopt -u nullglob
 
@@ -1258,7 +1263,7 @@ if [ "$action_names" ]; then
 	rm -f "${DIR}/*.image"
 
 	modmakedate=$(date +%Y%m%d-%H%M%S)
-	modbaseimagename="${FREETZ_TYPE_PREFIX_ALIEN_HARDWARE}${FREETZ_TYPE_PREFIX}_${FIRMWAREVERSION}-${SUBVERSION}.${FREETZ_TYPE_LANGUAGE}"
+	modbaseimagename="${FREETZ_TYPE_PREFIX_ALIEN_HARDWARE}${FREETZ_TYPE_PREFIX}${FREETZ_TYPE_PREFIX_LABOR_FIRMWARE}_${FIRMWAREVERSION}-${SUBVERSION}.${FREETZ_TYPE_LANGUAGE}"
 	if [ "$FREETZ_CUSTOM_IMAGE_NAME" == "y" -a ! -z "$FREETZ_USER_DEFINED_COMMENT" ]; then
 		modcustomimagestring=$(echo $FREETZ_USER_DEFINED_COMMENT | sed -e "s/ /_/g" | tr -cd 'a-zA-Z0-9_+-.<->')
 	else
@@ -1282,7 +1287,7 @@ if [ "$action_names" ]; then
 	# Create freetz-info
 	echo1 "integrate freetz info file into image"
 	freetz_info_file="$MOD_DIR/filesystem/etc/freetz_info.cfg"
-	echo "export FREETZ_INFO_BOXTYPE='${FREETZ_TYPE_PREFIX_ALIEN_HARDWARE}${FREETZ_TYPE_PREFIX}'" > "$freetz_info_file"
+	echo "export FREETZ_INFO_BOXTYPE='${FREETZ_TYPE_PREFIX_ALIEN_HARDWARE}${FREETZ_TYPE_PREFIX}${FREETZ_TYPE_PREFIX_LABOR_FIRMWARE}'" > "$freetz_info_file"
 	echo "export FREETZ_INFO_FIRMWAREVERSION='${FIRMWAREVERSION}'" >> "$freetz_info_file"
 	echo "export FREETZ_INFO_SUBVERSION='${SUBVERSION}'" >> "$freetz_info_file"
 	echo "export FREETZ_INFO_LANG='${FREETZ_TYPE_LANGUAGE}'" >> "$freetz_info_file"
