[freetz-1.1-stable] merge in r3140:r3146, r3149:r3150, r3155:rr3156, r3158:r3159, r3161:r3163, r3167:r3168, r3177, r3180, r3182:r3183, r3185:r3188, r3190:r3193 from trunk:  * firmwares:   * * Bump 3270 to 47.04.70  * packages:   * bip: bump to 0.8.0   * callmonitor: bump to 1.12.4   * dnsmasq: save pid-file in /var/run/dnsmasq/dnsmasq.pid so that dnsmasq can unlink it.   * gnu-make: Fix error with glob_t (see http://www.ip-phone-forum.de/showthread.php?t=182484)   * iptables: Put libs under root/usr/lib so they are copied by new logic (refs #406), makes patches/150-iptables.sh obsolete    * add layer-7 patch   * mini_fo: Fix typo in webinterface (with jffs2 enabled no bullet was displayed)   * openvpn: fix script-error openvpn_conf   * rrdtool: Fix libtool library search paths   * usbip: Bump to 0.1.7    * Move to unstable section   * tor: Patch by alpha1974    * Fixes handling of tor's secrect key file   * usbroot: Set package startlevel to 05 (very early) to execute deferrred hotplugging events before other packages start  * patches:   * Fix usbstorage patch for several boxes (2170, 3130, 3131, 3170, 7140, 7150)    * Fix strange mount points (e.g. uStorro2/1us/usb/001/0021)    * Remove outdated patches (closes #409)  * other:   * device table: Add /dev/sde and /dev/sdf   * rudi-shell: Fix quotation   * 7270: Add menuconfig option (Advanced Options) to reintegrate AVM plugins into firmware   * modlibrc: remove optional parameter for pidfile    * rc.*: change to PID_FILE variable   * config.mipsel: more configs for cross compiling.   * get_ip: Fix typo from r3128   * Change fwmod logic for inclusion of libraries.    * Fixes bug that glib2 is included when glib1 is selected.   * Change fwmod logic for inclusion of terminfos (according to r3162)    * Rename terminfo symbols (FREETZ_SHARE_terminfo)   * backup/restore function:    * Check for file named freetz in upload to avoid errors.    * fakeroot: version bump to 1.12.2
git-svn-id: http://svn.freetz.org/branches/freetz-stable-1.1@3194 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/fwmod b/fwmod
--- a/fwmod
+++ b/fwmod
@@ -175,12 +175,14 @@ TOOLS_SUBDIR="tools"
 SOURCE_SUBDIR="source"
 FIRMWARE_SUBDIR="firmware"
 FILESYSTEM_SUBDIR="filesystem"
+AVMPLUGINS_SUBDIR="plugins.image"
 EXTERNAL_SUBDIR="external"
 KERNEL_SUBDIR="kernel"
 VARTAR_SUBDIR="var.tar"
 
 KERNEL_IMAGE="var/tmp/kernel.image"
 
+AVMPLUGINS_FILE="var/tmp/plugins.update"
 RAW_KERNEL_FILE="kernel.raw"
 RAW_HIDDEN_FILE="kernelsquashfs.raw"
 VARTAR_FILE="var.tar"
@@ -383,12 +385,14 @@ ORG_DIR="${DIR}/original"
 FIRMWARE_DIR="${ORG_DIR}/${FIRMWARE_SUBDIR}"
 FILESYSTEM_DIR="${ORG_DIR}/${FILESYSTEM_SUBDIR}"
 KERNEL_DIR="${ORG_DIR}/${KERNEL_SUBDIR}"
+AVMPLUGINS_DIR="${KERNEL_DIR}/${AVMPLUGINS_SUBDIR}"
 VARTAR_DIR="${KERNEL_DIR}/${VARTAR_SUBDIR}"
 
 KERNEL="${FIRMWARE_DIR}/${KERNEL_IMAGE}"
 
 RAW_KERNEL="${KERNEL_DIR}/${RAW_KERNEL_FILE}"
 FILESYSTEM="${KERNEL_DIR}/${RAW_HIDDEN_FILE}"
+AVMPLUGINS="${FIRMWARE_DIR}/${AVMPLUGINS_FILE}"
 VARTAR="${FILESYSTEM_DIR}/${VARTAR_FILE}"
 
 if [ "$DO_UNPACK" -gt 0 ]; then
@@ -432,6 +436,20 @@ if [ "$DO_UNPACK" -gt 0 ]; then
 
 	chmod -R +w "$FILESYSTEM_DIR"
 
+	if [ -r "$AVMPLUGINS" ]; then
+		echo "unpacking AVM plugins"
+		mkdir -p "$AVMPLUGINS_DIR"
+		"$TAR" -xif "$AVMPLUGINS" -C "$AVMPLUGINS_DIR" || exit 1
+
+		for i in "${AVMPLUGINS_DIR}/var/"*.image; do
+			AVMPLUGIN="${i##*/plugin-}"
+			AVMPLUGIN="${AVMPLUGIN%\.image}"
+			echo1 "$AVMPLUGIN image"
+			modunsqfs "$AVMPLUGINS_DIR/plugin-${AVMPLUGIN}" "$i" > /dev/null
+		done
+		chmod -R +w "$AVMPLUGINS_DIR"
+	fi
+
 	if [ ! -r "$FILESYSTEM_DIR/var" ]; then
 		error 1 "could not unpack the filesystem image"
 	fi
@@ -467,6 +485,8 @@ FIRMWARE_MOD_DIR="${MOD_DIR}/${FIRMWARE_SUBDIR}"
 FILESYSTEM_MOD_DIR="${MOD_DIR}/${FILESYSTEM_SUBDIR}"
 EXTERNAL_MOD_DIR="${MOD_DIR}/${EXTERNAL_SUBDIR}"
 KERNEL_MOD_DIR="${MOD_DIR}/${KERNEL_SUBDIR}"
+AVMPLUGINS_MOD_DIR="${KERNEL_MOD_DIR}/${AVMPLUGINS_SUBDIR}"
+AVMPLUGINS_FILESYSTEM_MOD_DIR="${FILESYSTEM_MOD_DIR}/usr/share/avmplugins"
 VARTAR_MOD_DIR="${KERNEL_MOD_DIR}/${VARTAR_SUBDIR}"
 
 KERNEL_MOD="${FIRMWARE_MOD_DIR}/${KERNEL_IMAGE}"
@@ -652,6 +672,22 @@ if [ "$DO_MOD" -gt 0 ]; then
 		error 1 "please choose at least one OEM (branding) in menuconfig: AVM, 1&1, Freenet etc."
 	fi
 
+	# Copy selected avmplugins into the firmware
+	if [ "$FREETZ_AVMPLUGINS_ENABLED" == "y" ]; then
+		echo "installing AVM plugins"
+		echo "#" > ${FILESYSTEM_MOD_DIR}/sbin/start_plugin.sh
+		rm -rf ${FIRMWARE_MOD_DIR}/${AVMPLUGINS_FILE}
+		mkdir "${AVMPLUGINS_FILESYSTEM_MOD_DIR}"
+		for i in `find "${AVMPLUGINS_MOD_DIR}" -maxdepth 1 -type d -name var -prune -false , -type d -name "plugin-*"`; do
+			AVMPLUGIN="${i##*plugin-}"
+			if [ "$(eval "echo \"\$FREETZ_AVMPLUGINS_$(echo "$AVMPLUGIN" | tr [:lower:] [:upper:])\"")" == "y" ]; then
+				echo1 "$AVMPLUGIN plugin"
+				cp -a "${AVMPLUGINS_MOD_DIR}/plugin-${AVMPLUGIN}" "${AVMPLUGINS_FILESYSTEM_MOD_DIR}/plugin-${AVMPLUGIN}"
+				ln -s "/usr/share/avmplugins/plugin-${AVMPLUGIN}" "${VARTAR_MOD_DIR}/var/plugin-${AVMPLUGIN}"
+			fi
+		done
+	fi
+
 	if [ "$FREETZ_INSTALL_BASE" == "y" ]; then
 		echo "installing mod base"
 
@@ -701,42 +737,44 @@ if [ "$DO_MOD" -gt 0 ]; then
 		ln -s ../var/tmp/gshadow "${FILESYSTEM_MOD_DIR}/etc/gshadow"
 
 		echo1 "installing libs"
-			for i in \
-			$( \
-				 cd "${ROOT_DIR}" && \
-				 find lib usr/lib -type d -name .svn -prune -false , -type f -name "*.so*" \
-			)
-			do
-				bn="$(basename "$i")"
-				lib="${bn%\.so*}"
-				lib="$(echo "$lib" | sed -r 's/^libg(lib|object|module|thread)-2/libg\12-2/;s/-[0-9][\.0-9a-z]*$//')"
-				if [ "$(eval "echo \"\$FREETZ_LIB_$(echo "$lib" | tr '\-+' '_x')\"")" == "y" ]; then
-					echo2 "${bn}"
-					dn="$(dirname "$i")"
-					lib="$(echo "$lib" | sed -r 's/^libg(lib|object|module|thread)2/libg\1-2/')"
-					[ -d "${FILESYSTEM_MOD_DIR}/${dn}" ] || mkdir -p "${FILESYSTEM_MOD_DIR}/${dn}"
-					cp -a "${ROOT_DIR}/${dn}/${lib}"[-\|\.]*so* "${FILESYSTEM_MOD_DIR}/${dn}/"
-					chmod +x "${FILESYSTEM_MOD_DIR}/${i}"
+		for i in $(set | grep ^FREETZ_LIB_.*=y ); do
+			found=0
+			conf=${i%%=*}
+			bn=${conf#FREETZ_LIB_}
+			fn=${bn//_/[-+._]}
+			echo2 "$bn"
+			for dn in lib usr/lib usr/lib/xtables; do
+				files=$(shopt -s nullglob; echo ${ROOT_DIR}/$dn/$fn[-.]*so*)
+				if [ -z "$files" ]; then
+					continue;
 				fi
+				found=1
+				[ -d "${FILESYSTEM_MOD_DIR}/${dn}" ] || mkdir -p "${FILESYSTEM_MOD_DIR}/${dn}"
+				cp -a $files "${FILESYSTEM_MOD_DIR}/${dn}/"
 			done
+			if [ "$found" = 0 ]; then
+				warn "Library $bn selected, but no files found"
+			fi
+		done
 		[ "$FREETZ_LIB_libuClibc" == "y" ] && cp -a "${ROOT_DIR}/lib/libc.so.0" "${FILESYSTEM_MOD_DIR}/lib/"
 		
-		if [ "$FREETZ_LIB_libterminfo" == "y" ]; then
+		if [ "$FREETZ_SHARE_terminfo" == "y" ]; then
 			echo1 "installing terminfos"
-			for i in \
-			$( \
-				cd "${ROOT_DIR}" && \
-				find usr/share/terminfo -type d -name .svn -prune -false , -type f \
-			)
-			do
-				bn="$(basename "$i")"
-				terminfo="${bn}"
-				if [ "$(eval "echo \"\$FREETZ_LIB_libterminfo_$(echo "$terminfo" | sed 's/-/minus/g;s/+/plus/g;s/\./dot/g')\"")" == "y" ]; then
-					echo2 "${bn}"
-					dn="$(dirname "$i")"
-					[ -d "${FILESYSTEM_MOD_DIR}/${dn}" ] || mkdir -p "${FILESYSTEM_MOD_DIR}/${dn}"
-					cp -a "${ROOT_DIR}/${dn}/${terminfo}" "${FILESYSTEM_MOD_DIR}/${dn}/"
+			for i in $(set | grep ^FREETZ_SHARE_terminfo_.*=y |grep -v '^FREETZ_SHARE_terminfo_showall=' ); do
+				dn=usr/share/terminfo
+				conf=${i%%=*}
+				bn=${conf#FREETZ_SHARE_terminfo_}
+				fn=$(echo "$bn" | sed 's/MINUS/-/g;s/PLUS/+/g;s/\DOT/./g')
+				echo2 "$fn"
+				fn="${fn:0:1}/$fn"
+				file="${ROOT_DIR}/$dn/$fn"
+				if [ ! -e "$file" ]; then
+					warn "Terminfo $bn selected, but no file found"
+					continue;
 				fi
+				dest="${FILESYSTEM_MOD_DIR}/$dn/${fn:0:1}"
+				[ -d "$dest" ] || mkdir -p "$dest"
+				cp -a $file "$dest/"		
 			done
 		fi
 
@@ -990,13 +1028,13 @@ if [ "$DO_MOD" -gt 0 ]; then
 	# external should run after modifying and stripping and so on
 	# only run, if packaging is enabled
 
-  if [ "$DO_PACK" -gt 0 ]; then
-    if [ "$EXTERNAL_ENABLED" == "y" ]; then
-      echo "processing external"
-      [ ! -x "$EXTERNAL" ] && error 1 "cannot find the tool $EXTERNAL_TOOL"
-      . "${EXTERNAL}"
-    fi
-  fi
+	if [ "$DO_PACK" -gt 0 ]; then
+		if [ "$EXTERNAL_ENABLED" == "y" ]; then
+			echo "processing external"
+			[ ! -x "$EXTERNAL" ] && error 1 "cannot find the tool $EXTERNAL_TOOL"
+			. "${EXTERNAL}"
+		fi
+	fi
 
 	touch "${DIR}/.modified"
 	echo "done."
