fwmod:  * implement a very simple image-structure (actually tar-structure) consistency check  * we received reports (s. #2721 and [http://www.ip-phone-forum.de/showthread.php?t=277451 this ippf-thread]) stating that the created image files have "invalid tar magic"  * it is still unknown if it's a freetz, a busybox or a build-system issue  * the change is intended to make the build process fail much earlier, i.e. before the user tries to flash the corrupted image to the box  * refs #2721
git-svn-id: http://svn.freetz.org/trunk@13051 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/fwmod b/fwmod
--- a/fwmod
+++ b/fwmod
@@ -41,6 +41,14 @@ byte_to_mb() {
 	echo $(($1)) | awk ' { printf "%.1f MB", $1 /1024/1024 } '
 }
 
+# $1 - tarball filename
+is_valid_tarball() {
+	# integrity check by listing the content
+	[ -s "$1" ] && "$TAR" -tf "$1"    >/dev/null 2>&1
+
+	# integrity check by decompressing to stdout
+#	[ -s "$1" ] && "$TAR" -xf "$1" -O >/dev/null 2>&1
+}
 
 ##################################################
 ## Initialise and check command line parameters ##
@@ -1511,9 +1519,11 @@ if [ "$action_names" ]; then
 
 	# Pack var.tar (use old tar for compatibility)
 	echo0 "packing var.tar"
-	"$TAR" -C "$VARTAR_MOD_DIR" -cf "$VARTAR_MOD" . || exit 1
-
-	[ ! -s "$VARTAR_MOD" ] && error 1 "packing of var.tar failed"
+	"$TAR" -C "$VARTAR_MOD_DIR" -cf "$VARTAR_MOD" .
+	if [ $? -ne 0 ] || ! is_valid_tarball "$VARTAR_MOD"; then
+		mv "${VARTAR_MOD}" "${VARTAR_MOD}.corrupted" 2>/dev/null
+		error 1 "packing of var.tar failed"
+	fi
 
 	[ "$FREETZ_AVM_HAS_UDEV" == "y" ] || \
 		$MAKEDEVS -d $MAKEDEVS_FILE $FILESYSTEM_MOD_DIR > $MOD_DIR/filesystem.log 2>&1
@@ -1530,9 +1540,9 @@ if [ "$DO_ZIP" -gt 0 ]; then
 		zip_name="${DIR}/${modstring}_rootfs.tar.gz"
 	fi
 	echo0 "zipping root file system to $zip_name"
-	"$TAR" -C "$FILESYSTEM_MOD_DIR" -czf "$zip_name" . || exit 1
-	if [ ! -s "$zip_name" ]; then
-		rm -f "$zip_name"
+	"$TAR" -C "$FILESYSTEM_MOD_DIR" -czf "$zip_name" .
+	if [ $? -ne 0 ] || ! is_valid_tarball "$zip_name"; then
+		mv "${zip_name}" "${zip_name}.corrupted" 2>/dev/null
 		error 1 "zipping of root file system failed"
 	fi
 	echo "$zip_name" > "${DIR}/.rootfs_archive"
@@ -1671,9 +1681,9 @@ if [ "$DO_PACK" -gt 0 ]; then
 	# Pack firmware image (use old tar for compatibility)
 	img_name="${FW_IMAGES_DIR:-$DIR}/${modimage}"
 	echo0 "packing $img_name"
-	"$TAR" -C "$FIRMWARE_MOD_DIR" -cf "$img_name" . || exit 1
-	if [ ! -s "$img_name" ]; then
-		rm -f "$img_name"
+	"$TAR" -C "$FIRMWARE_MOD_DIR" -cf "$img_name" .
+	if [ $? -ne 0 ] || ! is_valid_tarball "$img_name"; then
+		mv "${img_name}" "${img_name}.corrupted" 2>/dev/null
 		error 1 "packing of firmware image failed"
 	fi
 	echo1 "image file size: $(byte_to_mb $(wc -c < "$img_name"))"
@@ -1690,9 +1700,9 @@ if [ "$action_names" ]; then
 		#static packages
 		modexternal="${FW_IMAGES_DIR:-$DIR}/${tplexternal}.external"
 		echo "packing ${modexternal}"
-		"$TAR" -C "$EXTERNAL_MOD_DIR" -cf "$modexternal" . || exit 1
-		if [ ! -s "$modexternal" ]; then
-			rm -f "$modexternal"
+		"$TAR" -C "$EXTERNAL_MOD_DIR" -cf "$modexternal" .
+		if [ $? -ne 0 ] || ! is_valid_tarball "$modexternal"; then
+			mv "${modexternal}" "${modexternal}.corrupted" 2>/dev/null
 			error 1 "packing of external tar failed"
 		fi
 		echo1 "external file size: $(byte_to_mb $(wc -c < "$modexternal"))"
@@ -1703,9 +1713,9 @@ if [ "$action_names" ]; then
 				pkg=${pkg#${EXTERNAL_MOD_DIR}-}
 				pkgexternal="${FW_IMAGES_DIR:-$DIR}/${tplexternal}_${pkg}.external"
 				echo "packing ${pkgexternal}"
-				"$TAR" -C "$EXTERNAL_MOD_DIR-${pkg}" -cf "$pkgexternal" . || exit 1
-				if [ ! -s "$pkgexternal" ]; then
-					rm -f "$pkgexternal"
+				"$TAR" -C "$EXTERNAL_MOD_DIR-${pkg}" -cf "$pkgexternal" .
+				if [ $? -ne 0 ] || ! is_valid_tarball "$pkgexternal"; then
+					mv "${pkgexternal}" "${pkgexternal}.corrupted" 2>/dev/null
 					error 1 "packing of external-$pkg tar failed"
 				fi
 				echo1 "package file size: $(byte_to_mb $(wc -c < "$pkgexternal"))"
