fwmod:  * use explicit {{{-a}}} while adding the TI-chksum - we expect kernel.image/filesystem.image not to contain the TI-chksum at this step and do want to fail if they do (without {{{-a}}}} tichksum-tool would just verify the chksum without failing)
git-svn-id: http://svn.freetz.org/trunk@14040 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/fwmod b/fwmod
--- a/fwmod
+++ b/fwmod
@@ -1732,7 +1732,7 @@ if [ "$DO_PACK" -gt 0 ]; then
 
 		fbn=$(basename $f)
 		echo0 "adding checksum to $fbn"
-		"$TICHKSUM" "$f" > "${MOD_DIR}/$fbn-chksum.log" || error 1 "adding checksum to $fbn failed"
+		"$TICHKSUM" -a "$f" > "${MOD_DIR}/$fbn-chksum.log" || error 1 "adding checksum to $fbn failed"
 	done
 
 	# Consistency check
