(logo) tagging: support for html&lua menu logos
git-svn-id: http://svn.freetz.org/trunk@9828 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/fwmod b/fwmod
--- a/fwmod
+++ b/fwmod
@@ -1137,36 +1137,34 @@ if [ "$DO_MOD" -gt 0 ]; then
 			dot_config_file="$MOD_DIR/filesystem/etc/.config"
 			cat "$DOT_CONFIG" | sed -e "s/#.*//g;/^$/d" > "$dot_config_file"
 		fi
-		# tagging
+
+		# logo tagging
 		if [ "$FREETZ_TAGGING_STRING" != "none" ]; then
+			tagging() {
+				[ $# -lt 3 ] && return
+				local tagging_geo="$1"
+				shift
+				local tagging_pos="$1"
+				shift
+				local tagging_arg="$*"
+				local tagging_pic="${TAGGING_DIR}/${FREETZ_TAGGING_STRING}.png"
+				for tagging_file in $tagging_arg; do
+					echo2 "${tagging_file}"
+					composite -dissolve 100% -gravity $tagging_pos -geometry $tagging_geo -quality 100 $tagging_pic $tagging_file $tagging_file
+					[ $? -ne 0 ] && error 1 "tagging failed while processing ${tagging_file#${FILESYSTEM_MOD_DIR}/}"
+				done
+			}
 			echo1 "tagging avm webif (tag by ${FREETZ_TAGGING_STRING})"
-			# newer (small logo @left, eg 7270 04.88)
-			if [ -z "$tagging_files" ]; then
-				tagging_files="$(find ${HTML_MOD_DIR} -name kopfbalken_links.gif)"
-				tagging_position="center"
-				tagging_geometry="+0+0"
-			fi
+			# newest lua (small logo @left, eg 7270 04.88)
+			tagging "+0+0" "center" $(find ${HTML_MOD_DIR} -name kopfbalken_links.gif)
+			# newer html (big header @top, eg 7320 05.29)
+			tagging "-20+0" "west" $(find ${HTML_MOD_DIR} -name kopfbalken.gif)
 			# older (big header @top, eg 7141 04.76)
-			if [ -z "$tagging_files" ]; then
-				tagging_files="$(find ${HTML_MOD_DIR} -name fw_header980.gif)"
-				tagging_position="west"
-				tagging_geometry="+0+0"
-			fi
+			tagging "+0+0" "west" $(find ${HTML_MOD_DIR} -name fw_header980.gif)
 			# even older (big header @top, eg 7050 04.03)
-			if [ -z "$tagging_files" ]; then
-				tagging_files="$(find ${HTML_MOD_DIR} -name fw_header.gif)"
-				tagging_position="west"
-				tagging_geometry="+0-5"
-			fi
-			# tagging
-			[ -z "$tagging_files" ] && error 1 "tagging failed, no files to tag found."
-			tagging_picture="${TAGGING_DIR}/${FREETZ_TAGGING_STRING}.png"
-			for tagging_file in $tagging_files; do
-				echo2 "${tagging_file}"
-				composite -dissolve 100% -gravity $tagging_position -geometry $tagging_geometry -quality 100 $tagging_picture $tagging_file $tagging_file
-				[ $? -ne 0 ] && error 1 "tagging failed while processing ${tagging_file#${FILESYSTEM_MOD_DIR}/}"
-			done
+			tagging "+0-5" "west" $(find ${HTML_MOD_DIR} -name fw_header.gif)
 		fi
+
 	fi
 
 	if [ "$FREETZ_STRIP_LIBRARIES" == "y" ]; then
