Generalise AVM junk byte detection and removal so as to save the manual work for each new labor firmware and to get rid of `FREETZ_AVM_JUNK_BYTES` with its ugly, long (256 bytes) content. Refs #1614.
git-svn-id: http://svn.freetz.org/trunk@8593 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/fwmod b/fwmod
--- a/fwmod
+++ b/fwmod
@@ -401,12 +401,13 @@ if [ "$DO_UNPACK" -gt 0 ]; then
 
 	# Remove AVM's special junk bytes from SquashFS
 	if [ "$FREETZ_HAS_AVM_JUNK_BYTES" == "y" ]; then
-		echo "removing AVM SquashFS junk bytes"
+		echo0 "removing AVM SquashFS junk bytes"
 		[ "$FREETZ_HAS_UPDATE_FILESYSTEM_IMAGE" == "y" ] && JUNK_BYTES_FILE="{FIRMWARE_DIR}/${FILESYSTEM_IMAGE}" || JUNK_BYTES_FILE="$KERNEL"
-		"$TOOLS_DIR/sfk" replace "$JUNK_BYTES_FILE" -bin "/$FREETZ_AVM_JUNK_BYTES//" -yes > /dev/null
-		_result=$?
-		[ $_result -eq 0 ] && error 1 "AVM SquashFS junk bytes not found"
-		[ $_result -gt 1 ] && error 1 "AVM SquashFS junk bytes matched $_result times (must be unique)"
+		[ "$FREETZ_VERBOSITY_LEVEL" -lt 2 ] \
+			&& "$TOOLS_DIR/remove-junk-bytes" "$JUNK_BYTES_FILE" "$JUNK_BYTES_FILE.nojunk" >/dev/null 2>&1 \
+			|| "$TOOLS_DIR/remove-junk-bytes" "$JUNK_BYTES_FILE" "$JUNK_BYTES_FILE.nojunk"
+		[ $? -eq 0 ] || error 1 "AVM SquashFS junk bytes not found"
+		mv -f "$JUNK_BYTES_FILE.nojunk" "$JUNK_BYTES_FILE"
 	fi
 
 	"$RMTICHKSUM" -f "${KERNEL}" > /dev/null
