fwmod: pimp error message

diff --git a/fwmod b/fwmod
--- a/fwmod
+++ b/fwmod
@@ -1572,14 +1572,14 @@ if [ "$DO_MOD" -gt 0 ]; then
 	if [ "$FREETZ_STRIP_LIBRARIES" == "y" ]; then
 		echo0 "shrinking shared libs"
 		source ${TOOLS_DIR}/freetz_mklibs
-		mklibs || error 1 "mklibs returned an error. Please see mklibs.log."
+		mklibs || error 1 "mklibs returned an error. Please see build/modified/mklibs.log"
 	fi
 	if  [ "$FREETZ_STRIP_MODULES_ALL" == "y" ]; then
 		echo0 "stripping all kernel modules"
 		for i in $(find ${MODULES_DIR} -name '*.ko'); do
 			echo2 $i
 			${ABS_BASE_DIR}/toolchain/kernel/bin/${FREETZ_KERNEL_CROSS}strip -p --strip-unneeded \
-				--remove-section={.comment,.pdr,.mdebug.abi32,.note.gnu.build-id} $i
+			  --remove-section={.comment,.pdr,.mdebug.abi32,.note.gnu.build-id} $i
 		done
 	fi
 	if [ "$FREETZ_STRIP_SCRIPTS" == "y" ]; then
