* mklibs: Move function from fwmod to tools/freetz_mklibs   * Remove old mklibs.py script   * Use patched debian mklibs package (patches taken from openwrt)   * see https://dev.openwrt.org/browser/trunk/tools/mklibs for details   * TODO:    * Provide static library libgcc_s_pic.a (simple copy/rename)    * Gives an error when relinking libc (only for uClibc-0.9.31)    * Provide pic files/versions of libraries   * refs #563
git-svn-id: http://svn.freetz.org/trunk@5826 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/fwmod b/fwmod
--- a/fwmod
+++ b/fwmod
@@ -872,86 +872,9 @@ if [ "$DO_MOD" -gt 0 ]; then
 	fi
 
 	if [ "$FREETZ_STRIP_LIBRARIES" == "y" ]; then
-		echo "shrink shared libs"
-		TARGET_TOOLCHAIN_STAGING_DIR="${ABS_BASE_DIR}/toolchain/target"
-
-		# TODO: replace the next 5 lines with code that replaces all
-		# absolute sym links... to make mklibs.py happy
-		ln -sf libcapi20.so.3.0.4 "${FILESYSTEM_MOD_DIR}/lib/libcapi20.so"
-		ln -sf libcapi20.so.3.0.4 "${FILESYSTEM_MOD_DIR}/lib/libcapi20.so.3"
-		ln -sf libfwsign.so "${FILESYSTEM_MOD_DIR}/lib/libfwsign.so.0"
-		ln -sf libled2.so.2.2.0 "${FILESYSTEM_MOD_DIR}/lib/libled2.so.2.2"
-		ln -sf libled2.so.2.2.0 "${FILESYSTEM_MOD_DIR}/lib/libled2.so.2"
-
-		# move shared libs from /lib and /usr/lib to libs_to_reduce folder
-		# this is fundamental for mklibs.py !!
-		# all needed lib are copied by mklibs.py to dest path (mklibs.py -d param)
-		CUR=`pwd`
-		rm -rf libs_to_reduce
-		mkdir libs_to_reduce
-		for SODIR in ${FILESYSTEM_MOD_DIR}/lib ${FILESYSTEM_MOD_DIR}/usr/lib; do
-			cd $CUR/$SODIR
-			for i in `find -maxdepth 1 -name "*.so*"`; do
-				mv $i $CUR/libs_to_reduce/$i;
-			done
-		done
-		cd $CUR
-
-		# when mklibs.py breaks with errors like "X unresolved non weak symbols: ...."
-		# you should search with grep, mc, readelf -s which binary needs this symbols
-		# and which lib provides this symbol ... you get some debug output when you "
-		# add some -v -v -v to mklibs.py call
-
-		# get_UserAgentTransport is referenced by libfon.so but not provided by
-		# any shared lib or binary
-		# __cxa_pure_virtual is referenced at some places..
-		UNNEEDED_SYMBOLS="-u get_UserAgentTransport -u __cxa_pure_virtual"
-
-		# some more referenced symbols not provided on 3170, this box does not have tr069
-		# but this should not break compatibility for other boxes
-		UNNEEDED_SYMBOLS+=" -u __cxa_atexit -u add_node -u add_object -u get_ctlmgr_value -u set_ctlmgr_value"
-
-		if [ "$FREETZ_REMOVE_TR069" == "y" ]; then
-			# ignore some symbols provided by libtr069.so and referenced at
-			# some places e.g. in libfon.so libwlan.so
-			UNNEEDED_SYMBOLS+=" -u get_ctlmgr_value -u _ZN14ModuleRegistry12ApplyChangesEv \
-				-u get_UIModule -u getNode -u cm_create_node -u GetContext \
-				-u _Z23TR069_SOAPEnvelope_FreeP18TR069_SOAPEnvelope -u findRefNodeOfName \
-				-u TR069_Helper_Parse_SOAP -u _ZN14ModuleRegistry19TransactionRollbackEv \
-				-u Unregister_VOIP_1und1_Assi -u _ZN14ModuleRegistry17TransactionCommitEv \
-				-u Register_VOIP_1und1_Assi -u get_NumberOfEntries -u _fLog -u remove_node \
-				-u _Z20Get_g_pParamRegistryv -u _ZN14ModuleRegistry17SetParameterValueEPcS0_ \
-				-u get_ExternalIPAddress -u _ZN14ModuleRegistry16TransactionBeginEv"
-		else
-			# set_PPPoEServiceName is referenced by libtr069.so but not
-			# provided by and shared lib or binary
-			UNNEEDED_SYMBOLS+=" -u set_PPPoEServiceName"
-		fi
-
-		#find all executables which uses parts of shared objects
-		find "${FILESYSTEM_MOD_DIR}" -type f -perm +100 -exec \
-			file -r -N -F '' {} + | \
-			awk ' /executable.*dynamically/ { print $1 }; /shared object/ {print $1} ' > "${FILESYSTEM_MOD_DIR}/mklibs-progs"
-
-		#we need the rest of shared objects in mod dir too
-		#iptables shared libs... ctlrmg shared libs
-		for i in `find "${FILESYSTEM_MOD_DIR}" -type f -name "*.so"`; do
-			echo $i >> "${FILESYSTEM_MOD_DIR}/mklibs-progs"
-		done
-
-		PATH=${TARGET_TOOLCHAIN_STAGING_DIR}/bin:$PATH tools/mklibs.py -v \
-			--target mipsel-linux-uclibc \
-			--ldlib ld-uClibc.so.0 \
-			--root ${FILESYSTEM_MOD_DIR} \
-			-d ${FILESYSTEM_MOD_DIR}/lib \
-			-D \
-			-L ${CUR}/libs_to_reduce \
-			-L ${TARGET_TOOLCHAIN_STAGING_DIR}/lib \
-			${UNNEEDED_SYMBOLS} \
-			`cat "${FILESYSTEM_MOD_DIR}/mklibs-progs"` > "${DIR}/modified/mklibs.log" 2>&1
-
-		rm -rf libs_to_reduce
-		rm -f ${FILESYSTEM_MOD_DIR}/mklibs-progs
+		echo0 "shrink shared libs"
+		. ${TOOLS_DIR}/freetz_mklibs
+		mklibs || error 1 "mklibs returned an error. Please see mklibs.log."
 	fi
 
 	echo0 "stripping leftover unstripped binaries"
