fwmod:  * add checksum to both {{{kernel.image}}} and {{{filesystem.image}}} (the latter one only if it has non-zero size)  * up to now we added it (for some unknown reasons) only to {{{kernel.image}}}  * silences the following warning while flashing the firmware {{{ File doesn't contain the checksum, adding [cs_calc_sum] sum 0x01020304 Calculated checksum is 01020304 [cs_set_sum] tagged 0 write 0x23de53c4, 0x04030201 MAGIC 0xc453de23 Adding failed }}}
git-svn-id: http://svn.freetz.org/trunk@13897 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/fwmod b/fwmod
--- a/fwmod
+++ b/fwmod
@@ -1727,7 +1727,13 @@ if [ "$DO_PACK" -gt 0 ]; then
 	fi
 
 	# Write checksum
-	"$TICHKSUM" "$KERNEL_MOD" > "${MOD_DIR}/kernelchksum.log"
+	for f in "$KERNEL_MOD" "$FILESYSTEM_MOD"; do
+		[ -s "$f" ] || continue
+
+		fbn=$(basename $f)
+		echo0 "adding checksum to $fbn"
+		"$TICHKSUM" "$f" > "${MOD_DIR}/$fbn-chksum.log" || error 1 "adding checksum to $fbn failed"
+	done
 
 	# Consistency check
 	if [ -s "${FIRMWARE_DIR}/${KERNEL_IMAGE}" -a ! -s "${FIRMWARE_MOD_DIR}/${KERNEL_IMAGE}" ] || \
