[freetz-stable-1.1] Merge in r3561, r3581, r3585, r3587:r3591, r3593:r3595, r3596:r3597, r3602, r3604, r3607, r3613:r3615, r3617, r3619, r3621:r3627, r3629:r3631, r3635, r3640:r3641 from trunk:  * firmware version bumps:   * 3270: 47.04.76   * 7113: 60.04.68   * 7140 A-CH: 39.04.76   * 7170 A-CH, EN: 04.76  * packages:   * Update callmonitor to version 1.15.1   * iptables-cgi: Reactivate for kernel 2.6.19.2 (patch by reiffert)   * usbroot: fixed version for w900v by loomes   * dnsmasq: bump version to 2.50 (security update)  * patches:   * remove tr069: split patch into 2 parts, because tr069fwupdate is needed for updating mt-d-devices   * enable "remove tr069" and "remove dtrace" for 7113   * disable "remove usermand" for 3170 if the kernel is replaced   * 7150: Fix autorun/autoend patches  * others:   * when changing (web interface) password, verify old one.   * fwmod: fix utf-8 problem   * modhosts: include /etc/init.d/rc.conf to fix nslookup   * get_ip: make "-d" the default until "-w" gets session ID support   * modusers: Add explicit chmod for shadow and gshadow    * New files are created correctly but existing ones can have wrong permissions   * Changes to webinterface width didn't show up until rc.webcfg was restarted from command line    * This was caused because $_cgi_width was set when restarting through the webif it self   * removes obsolete kernel sources (04.29, 04.30, 12043, 7270, r4884 and r8508)   * removes obsolete REMOVE_BRANDING_congstar   * add some optimizations for kernel build   * Fix swapfile creation button for IE    * Fix swapfile popup window
git-svn-id: http://svn.freetz.org/branches/freetz-stable-1.1@3646 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/fwmod b/fwmod
--- a/fwmod
+++ b/fwmod
@@ -27,7 +27,7 @@
 # This script is based on Christian Volkmann's fritzbox mod-0.57.
 # Legacy URL: http://www.ip-phone-forum.de/showthread.php?t=65894
 #
-# Special Thanks to Andreas Bühmann, Christian Volkmann, Enrik Berkhan,
+# Special Thanks to Andreas Buehmann, Christian Volkmann, Enrik Berkhan,
 # SpeedyBZ and all members on ip-phone-forum.de who contributed to this mod
 
 SHELL=$BASH
@@ -171,13 +171,6 @@ EXTERNAL_TOOL="external"
 MKSQUASHFS_OPTIONS="-le -noappend -all-root -info"
 UNSQUASHFS_OPTIONS="-no-progress"
 
-if [ "$FREETZ_REPLACE_KERNEL" == "y" ] || [ "$FREETZ_KERNEL_VERSION_2_6_19_2" ]; then
-	MKSQUASHFS_TOOL="mksquashfs3-lzma"
-	MKSQUASHFS_OPTIONS+=" -no-progress -no-exports -no-sparse"
-else
-	MKSQUASHFS_TOOL="mksquashfs-lzma"
-fi
-
 TAR_TOOL="tar"
 
 TOOLS_DIR="${ABS_BASE_DIR}/${TOOLS_SUBDIR}"
@@ -204,6 +197,23 @@ DYNAMIC_PACKAGES_FILE="${BASE_DIR}/.dynamic"
 STATIC_ADDON_FILE="${ADDON_DIR}/static.pkg"
 DYNAMIC_ADDON_FILE="${ADDON_DIR}/dynamic.pkg"
 
+
+# Config file readable?
+if [ ! -r "$DOT_CONFIG" ]; then
+	echo -e "ERROR: not configured" 1>&2
+	exit 1
+fi
+
+# Load config
+. "$DOT_CONFIG"
+
+if [ "$FREETZ_REPLACE_KERNEL" == "y" ] || [ "$FREETZ_KERNEL_VERSION_2_6_19_2" ]; then
+	MKSQUASHFS_TOOL="mksquashfs3-lzma"
+	MKSQUASHFS_OPTIONS+=" -no-progress -no-exports -no-sparse"
+else
+	MKSQUASHFS_TOOL="mksquashfs-lzma"
+fi
+
 # Dot-include 'modpatch' shell function
 . "${TOOLS_DIR}/freetz_patch"
 
@@ -214,11 +224,6 @@ DYNAMIC_ADDON_FILE="${ADDON_DIR}/dynamic.pkg"
 # Dont run this script as root
 if [ $UID -eq 0 ]; then
 	error 1 "running this script as root is prohibited"
-fi
-
-# Config file readable?
-if [ ! -r "$DOT_CONFIG" ]; then
-	error 1 "not configured"
 fi
 
 if [ -z "$FIRMWARE" ]; then
@@ -235,10 +240,6 @@ fi
 if [ ! -e "$DIR" ]; then
 	mkdir -p "$DIR"
 fi
-
-# Load config
-. "$DOT_CONFIG"
-
 
 ############################################
 ## Unpack and unsquash the firmware image ##
@@ -538,8 +539,8 @@ if [ "$DO_MOD" -gt 0 ]; then
 		echo
 	fi
 
-	if isFreetzType W501V W701V W900V; then
-		oem_list="tcom congstar avm"
+	if isFreetzType W501V; then
+		oem_list="tcom avm"
 	fi
 	sed -i -r -e 's/for i in  (avm|tcom).*; do/for i in '"$oem_list"' ; do/g' "${FIRMWARE_MOD_DIR}/var/install"
 
