fwmod: fix indendation

diff --git a/fwmod b/fwmod
--- a/fwmod
+++ b/fwmod
@@ -299,29 +299,29 @@ validate_signature() {
 		rm -rf "$TMP"
 		[ $RET -ne 0 ] && error $RET "image could not be verified with public key"
 	else
-	# img
-	cat "$2" > "$TMP/img"
-	# fix
-	local FIX="$(mktemp -p $TMP)"
-	"$TAR_GNU" -f "$TMP/img"  --owner=0 --group=0 --mode=0755 --format=oldgnu  -C "$TMP"  --append  ${FIX##*/}
-	# sig
-	"$TAR_GNU" -f "$TMP/img"  --owner=0 --group=0 --mode=0755 --format=oldgnu  -C "$TMP"  --extract ./var/signature --transform='s!.*!sig!'
-	"$TAR_GNU" -f "$TMP/img"  --owner=0 --group=0 --mode=0755 --format=oldgnu             --delete  ./var/signature ${FIX##*/}
-	# key
-	{
-		echo -n 'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQ==' | base64 -d
-		echo -n "$MOD" | while read -n2 x; do echo -ne "\x$x"; done
-		echo -ne "\x2"
-		echo -ne "\x$((${#EXP}/2))"
-		echo -n "$EXP" | while read -n2 x; do echo -ne "\x$x"; done
-	} > "$TMP/key"
-	# chk
-	VAL="$(openssl md5 -verify "$TMP/key" -keyform der -signature "$TMP/sig" "$TMP/img" 2>&1)"
-	RET="$?"
-	# clr
-	rm -rf "$TMP"
-	# act
-	[ "$RET" != "0" ] && echo -e "\033[0;31mfailed\033[0m\nOpenSSL: $VAL" && error 1 "image could not be verified with public key"
+		# img
+		cat "$2" > "$TMP/img"
+		# fix
+		local FIX="$(mktemp -p $TMP)"
+		"$TAR_GNU" -f "$TMP/img"  --owner=0 --group=0 --mode=0755 --format=oldgnu  -C "$TMP"  --append  ${FIX##*/}
+		# sig
+		"$TAR_GNU" -f "$TMP/img"  --owner=0 --group=0 --mode=0755 --format=oldgnu  -C "$TMP"  --extract ./var/signature --transform='s!.*!sig!'
+		"$TAR_GNU" -f "$TMP/img"  --owner=0 --group=0 --mode=0755 --format=oldgnu             --delete  ./var/signature ${FIX##*/}
+		# key
+		{
+			echo -n 'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQ==' | base64 -d
+			echo -n "$MOD" | while read -n2 x; do echo -ne "\x$x"; done
+			echo -ne "\x2"
+			echo -ne "\x$((${#EXP}/2))"
+			echo -n "$EXP" | while read -n2 x; do echo -ne "\x$x"; done
+		} > "$TMP/key"
+		# chk
+		VAL="$(openssl md5 -verify "$TMP/key" -keyform der -signature "$TMP/sig" "$TMP/img" 2>&1)"
+		RET="$?"
+		# clr
+		rm -rf "$TMP"
+		# act
+		[ "$RET" != "0" ] && echo -e "\033[0;31mfailed\033[0m\nOpenSSL: $VAL" && error 1 "image could not be verified with public key"
 	fi
 	echo -e "\033[0;32mvalid\033[0m"
 }
