fwmod "remove junk bytes"-step:  * distinguish between "no junk bytes found" (=>warning) and all other error cases (=>fatal errors)  * refs #2703
git-svn-id: http://svn.freetz.org/trunk@13348 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/fwmod b/fwmod
--- a/fwmod
+++ b/fwmod
@@ -428,11 +428,11 @@ if [ "$DO_UNPACK" -gt 0 ]; then
 		else
 			"$TOOLS_DIR/remove-junk-bytes" "$JUNK_BYTES_FILE" "$JUNK_BYTES_FILE.nojunk"
 		fi
-		if [ $? -ne 0 ]; then
-			warn2 "AVM SquashFS junk bytes not found. Assuming Freetz or Freetz-repacked image."
-		else
-			mv -f "$JUNK_BYTES_FILE.nojunk" "$JUNK_BYTES_FILE"
-		fi
+		case "$?" in
+			0) mv -f "$JUNK_BYTES_FILE.nojunk" "$JUNK_BYTES_FILE" ;;
+			1) warn2 "AVM SquashFS junk bytes not found. Assuming Freetz or Freetz-repacked image." ;;
+			*) error 1 "fatal error while removing AVM SquashFS junk bytes." ;;
+		esac
 	fi
 
 	"$TICHKSUM" -r "${KERNEL}" > /dev/null
