get_ip: add ipv6&prefix by ctlmgr_ctl, thx Whoopie (closes #2121)

diff --git a/make/mod/files/root/usr/bin/get_ip b/make/mod/files/root/usr/bin/get_ip
--- a/make/mod/files/root/usr/bin/get_ip
+++ b/make/mod/files/root/usr/bin/get_ip
@@ -11,8 +11,10 @@ get_ip - determine external IP address
 
 Usage: $0 [option]
     -a, --all      - use all methods (order: stun, route, dsld, webcm) [recommended]
-    -6  --ipv6     - IPv6 address
-    -p, --pre6     - IPv6 prefix
+    -6, --ipv6     - IPv6 address (showdsldstat)
+    -p, --pre6     - IPv6 prefix (showdsldstat)
+        --gua      - IPv6 address (ctlmgr_ctl)
+        --pd       - IPv6 prefix (ctlmgr_ctl)
     -d, --dsld     - use showdsldstat (since firmware 04.86)
     -r, --route    - use routing table
     -s, --stun     - use STUN/VoIP (server: $MOD_GET_IP_STUN)
@@ -116,6 +118,18 @@ case $1 in
 		;;
 	-p|--pre6)
 		VAL="$(showdsldstat 2>/dev/null | sed -rn 's/.* IPv6: prefix ([^ ]*).*/\1/p')"
+		[ -z "$VAL" ] && echo "get_ip error" >&2 && exit 1
+		echo "$VAL"
+		exit
+		;;
+	--gua)
+		VAL="$(ctlmgr_ctl r ipv6 settings/ip)"
+		[ -z "$VAL" ] && echo "get_ip error" >&2 && exit 1
+		echo "$VAL"
+		exit
+		;;
+	--pd)
+		VAL="$(ctlmgr_ctl r ipv6 settings/prefix)"
 		[ -z "$VAL" ] && echo "get_ip error" >&2 && exit 1
 		echo "$VAL"
 		exit
