Partial revert of r8321: revive internal `get_ip` methods webcm and dsld methods as fallbacks for cases in which the route method fails to determine the external IP. Method extquery is still obsolete (STUN is functionally equivalent but more efficient, plus wget needed by extquery is not mandatory for Busybox). So is ostat because it returns outdated IPs in known cases when onlinechanged was not called at reconnect. Refs #1644.
git-svn-id: http://svn.freetz.org/trunk@8339 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/make/mod/files/root/usr/bin/get_ip b/make/mod/files/root/usr/bin/get_ip
--- a/make/mod/files/root/usr/bin/get_ip
+++ b/make/mod/files/root/usr/bin/get_ip
@@ -10,9 +10,11 @@ cat << EOF
 get_ip - determine external IP address
 
 Usage: $0 [option]
-    -a, --all      - use all methods (order: stun, route) [recommended]
-    -s, --stun     - use STUN server (stun.1und1.de)
+    -a, --all      - use all methods (order: stun, route, dsld, webcm) [recommended]
+    -d, --dsld     - use showdsldstat (since firmware 04.86)
     -r, --route    - use routing table
+    -s, --stun     - use STUN server (stun.1und1.de)
+    -w, --webcm    - use webcm CGI handler / ctlmgr_ctl
     -?, --help     - print this help message
 
   current default method: $MOD_GET_IP_METHOD
@@ -36,6 +38,12 @@ ip_public()
 	[ "$ip" == "${ip#172.}" ] && return 0
 	ip=$(echo $ip | cut -d '.' -f 2)
 	[ $ip -ge 16  ] && [ $ip -le 31 ] && return 1 || return 0
+}
+
+via_dsld() {
+	# Firmware ca. 04.68 and newer should be safe, but some boxes had it since 04.31
+	IP="$(/sbin/showdsldstat 2>/dev/null | sed -nr 's/0: ip ([0-9.]+).*/\1/p')"
+	ip_public "$IP" || return 1
 }
 
 # AVM's home-brew NAT does not expose the external IP on network interface
@@ -69,15 +77,46 @@ via_stun() {
 	return 1
 }
 
+via_webcm() {
+	local queryfile="/usr/www/all/html/query.txt"
+	local querystring=""
+	if which ctlmgr_ctl >/dev/null; then
+		# Firmware ca. 04.76 and newer
+		IP=$(ctlmgr_ctl r connection0 pppoe:status/ip)
+	else
+		if [ "$(sed -n '/var:n\[/p' $queryfile)" ]; then
+			# Firmware ca. 04.84 and newer (should never be used, see above)
+			querystring="var:n[0]=connection0:pppoe:status/ip"
+		else
+			# Older firmware
+			querystring="var:cnt=1&var:n0=connection0:pppoe:status/ip"
+		fi
+		IP="$(/usr/www/html/cgi-bin/webcm "getpage=${queryfile}&${querystring}")"
+	fi
+	# ctlmgr_ctl return values [box=val]: 7170=176, 7270=177, 7141=172
+	# Caveat: must use "-o" instead of "||", otherwise "$?" would be reset
+	[ $? -eq 0 -o $? -ge 170 ] && ip_public "$IP" && return 0 || return 1
+}
+
 # Set user-defined method (e.g. via web UI) if no argument is given
 [ $# -eq 0 ] && method="$MOD_GET_IP_METHOD" || method="$1"
 
 case $method in
-	-a|--all|"")
-		for mode in stun route; do
+	-a|--all|""|-e|--extquery|-o|--ostat)
+		[ "$method" ] && [ "$method" != "-a" ] && [ "$method" != "--all" ] &&
+			echo "warning: method $method is obsolete, using --all instead" >&2
+		# Why this order?
+		#   1.) STUN should always work and is fast
+		#   2.) route is fast, works in all firmwares, problematic routing configs are rare
+		#   3.) dsld is faster than ctlmgr/webcm, but not always available
+		#   4.) ctlmgr/webcm is slow, but should work in all firmwares on DSL boxes
+		for mode in stun route dsld webcm; do
 			via_$mode
 			[ $? -eq 0 ] && break
 		done
+		;;
+	-d|--dsld)
+		via_dsld
 		;;
 	-r|--route)
 		via_route
@@ -85,13 +124,8 @@ case $method in
 	-s|--stun)
 		via_stun
 		;;
-	-d|--dsld|-o|--ostat|-w|--webcm)
-		echo "warning: method $method is obsolete, using --route instead" >&2
-		via_route
-		;;
-	-e|--extquery)
-		echo "warning: method $method is obsolete, using --stun instead" >&2
-		via_stun
+	-w|--webcm)
+		via_webcm
 		;;
 	-?|-h|--help)
 		helpmsg
