get_ip  * dsld: check for local ips too (seen on  7141)  * dsld: update showdsldstat parsing, by kriegaex  * webcm: allow more returnvalues, see file for details (refs #525)
git-svn-id: http://svn.freetz.org/trunk@7375 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/make/mod/files/root/usr/bin/get_ip b/make/mod/files/root/usr/bin/get_ip
--- a/make/mod/files/root/usr/bin/get_ip
+++ b/make/mod/files/root/usr/bin/get_ip
@@ -15,10 +15,23 @@ echo "get_ip - determine external IP address"
 	echo
 }
 
+# dont return local-ips like 192.168.178.1
+check_local_ip() {
+	[ $retval -ne 0 ] && return
+	for local_ip in $(ifconfig | sed -n 's/.*inet addr:\([0-9\.]*\) .*/\1/p'); do
+		if [ "$local_ip" == "$ip" ]; then
+			ip=""
+			retval=3
+			break
+		fi
+	done
+}
+
 via_dsld() {
-	ip="$(/sbin/showdsldstat | grep "0: ip" | cut -d\/ -f1 | cut -d ' ' -f3)"
+	ip="$(/sbin/showdsldstat | sed -nr 's/0: ip ([0-9.]+).*/\1/p')"
 	retval=$?
 	[ -z "$ip" ] && retval=2
+	check_local_ip
 }
 
 via_extquery() {
@@ -51,15 +64,8 @@ via_webcm() {
 		ip="$(/usr/www/html/cgi-bin/webcm "getpage=${queryfile}&${querystring}")"
 		retval=$?
 	fi
-	[ $retval -eq 176 ] && retval=0 	# fix return-value of webcm
-	#do not return a local ip:
-	for local_ip in $(ifconfig | sed -n 's/.*inet addr:\([0-9\.]*\) .*/\1/p'); do
-		if [ "$local_ip" == "$ip" ]; then
-			ip=""
-			retval=3
-			break
-		fi
-	done
+	[ $retval -ge 170 ] && retval=0 	# i get [box=val]: 7170=176, 7270=177, 7141=172
+	check_local_ip
 }
 
 
@@ -91,7 +97,7 @@ esac
 
 if [ $retval -eq 0 ]; then
 	echo "$ip"
-	exit 0
+else
+	echo "get_ip error (exit code $retval)" >&2
 fi
-echo "get_ip error (exit code $retval)" >&2
 exit $retval
