Bump downloader to version 0.2 (by hermann72pb)
git-svn-id: http://svn.freetz.org/trunk@1657 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/packages/downloader-0.2/root/usr/bin/downloader b/packages/downloader-0.2/root/usr/bin/downloader
--- a/packages/downloader-0.2/root/usr/bin/downloader
+++ b/packages/downloader-0.2/root/usr/bin/downloader
@@ -13,15 +13,6 @@ if [ ! -r "$CONFPATH$CONFFILE" ]; then
 fi
 . $CONFPATH$CONFFILE
 
-echo $DOWNLOADER_SRVPRFX
-echo $DOWNLOADER_SRVUSR
-echo $DOWNLOADER_SRVPWD
-echo $DOWNLOADER_SRVURL
-echo $DOWNLOADER_SRVDIR
-echo $DOWNLOADER_NREP
-echo $DOWNLOADER_TWAIT
-
-
 ISFTP=$(echo $DOWNLOADER_SRVPRFX | grep -c ftp://)
 if [ $ISFTP -eq 1 ] ; then 
    if [ "$DOWNLOADER_SRVUSR" ] ; then
@@ -42,21 +33,26 @@ else
 	  exit 1
    fi    
 fi
-echo $SERVERSTR
+echo "Downloading of $LOADFILE from $SERVERSTR:"
 
 LOADERROR=1 # erstmal als erfolglos definieren
 II=1   # II zu 1 setzen
 while test $II -le $DOWNLOADER_NREP    # While-Schleife, emulieren einer for-schleife II<NN
 do
-   echo "ping test $II of $DOWNLOADER_NREP. Waiting $DOWNLOADER_TWAIT sec. for $DOWNLOADER_SRVURL"
-   sleep $DOWNLOADER_TWAIT
-   if (ping -c 1 $DOWNLOADER_SRVURL) ; then
-		echo -n "$LOADFILE.gz is downloading from $DOWNLOADER_SRVURL... "
-        wget -q -O $LOCALDR/$LOADFILE.gz $SERVERSTR$LOADFILE.gz
-        LOADERROR=$?       
-        break   #  alles ok, raus aus der for-schleife
+   echo -n "1. Ping test $II of $DOWNLOADER_NREP for $DOWNLOADER_SRVURL... "
+   if (ping -c 1 $DOWNLOADER_SRVURL > /dev/null 2>&1) ; then
+	echo "done"	
+	echo -n "2. $LOADFILE.gz is downloading from $DOWNLOADER_SRVURL... "
+       wget -q -O $LOCALDR/$LOADFILE.gz $SERVERSTR$LOADFILE.gz
+       LOADERROR=$?       
+       break   #  alles ok, raus aus der for-schleife
+   else
+	echo "failed"
    fi
    II=`expr $II + 1`     # Zähler inkrementieren
+   echo -n "1a. Waiting $DOWNLOADER_TWAIT sec... "
+   sleep $DOWNLOADER_TWAIT
+   echo "done"	
 done
 if [ $LOADERROR -eq 1 ]; then
    echo "failed"
@@ -66,8 +62,20 @@ if [ $LOADERROR -eq 1 ]; then
    exit $LOADERROR
 fi
 echo "done"
-echo -n "$LOADFILE.gz is unpacking... "
-gzip -d $LOCALDR/$LOADFILE.gz
+if test -e $LOCALDR/$LOADFILE ; then
+   echo -n "2a. $LOCALDR/$LOADFILE exists already. $LOADFILE is deleting... "
+   chmod "777" $LOCALDR/$LOADFILE
+   rm -f $LOCALDR/$LOADFILE
+   LOADERROR=$?
+   if [ $LOADERROR -eq 1 ]; then
+      echo "failed"
+      echo "file $LOCALDR/$LOADFILE could not be deleted"
+      exit $LOADERROR
+   fi
+   echo "done"
+fi 
+echo -n "3. $LOADFILE.gz is unpacking... "
+gzip -df $LOCALDR/$LOADFILE.gz
 LOADERROR=$?
 if [ $LOADERROR -eq 1 ]; then
    echo "failed"
@@ -75,7 +83,7 @@ if [ $LOADERROR -eq 1 ]; then
    exit $LOADERROR
 fi
 echo "done"
-echo -n "permitions for $LOADFILE are setting... "
+echo -n "4. permitions for $LOADFILE are setting... "
 chmod $FILEPERM $LOCALDR/$LOADFILE
 LOADERROR=$?
 if [ $LOADERROR -eq 1 ]; then
