phonebook-tools:  * exit with proper error code if phone book cannot be read  * refs #2568
git-svn-id: http://svn.freetz.org/trunk@12535 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/make/phonebook-tools/files/root/usr/bin/phonebook-tools b/make/phonebook-tools/files/root/usr/bin/phonebook-tools
--- a/make/phonebook-tools/files/root/usr/bin/phonebook-tools
+++ b/make/phonebook-tools/files/root/usr/bin/phonebook-tools
@@ -477,7 +477,12 @@ if [ "${BOOK}" = "active" ]; then
 fi
 
 # process
-retrieve_book_${METHOD} | $DOS2UNIX | linearize ' ' | normalize_whitespaces | fix_join_effects | remove_unnecessary_var_flash_only_elements | ensure_well_formed_xml | filter_by_book_id | {
+set -o pipefail
+
+pb_content=$(retrieve_book_${METHOD}) # might fail, thus no direct piping
+rc=$?; [ $rc -ne 0 ] && exit $rc
+
+echo -n "${pb_content}" | $DOS2UNIX | linearize ' ' | normalize_whitespaces | fix_join_effects | remove_unnecessary_var_flash_only_elements | ensure_well_formed_xml | filter_by_book_id | {
 	case "${TO}" in
 		tsv)
 			to_tsv
