ppp-cgi: some cosmetics
git-svn-id: http://svn.freetz.org/trunk@9347 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/make/ppp-cgi/files/root/etc/default.ppp/ppp_observer b/make/ppp-cgi/files/root/etc/default.ppp/ppp_observer
--- a/make/ppp-cgi/files/root/etc/default.ppp/ppp_observer
+++ b/make/ppp-cgi/files/root/etc/default.ppp/ppp_observer
@@ -13,7 +13,7 @@ willkommen() {
 
 bisbald () {
 	HURET=1
-		while [ $HURET -ne 0 ]; do
+	while [ $HURET -ne 0 ]; do
 		[ "$PPP_FALLBACK" != 'yes' ] || echo -e "\n$(date): HANGUP" >> $PPP_FABALOG
 		/etc/init.d/rc.ppp disconnect
 		HURET=$?
@@ -23,7 +23,7 @@ bisbald () {
 reanimiert () {
 	[ -n "$ALIVEIP" ] && route del $ALIVEIP 2>/dev/null
 	if [ -z "$ALIVEIP" -a -z "$CURRENT_ROUTE" ]; then
-		echo "############################# CHECK NICHT MÖGLICH: Verbindung wird nicht automatisch getrennet!" >> $PPP_FABALOG
+		echo "############################# CHECK NICHT MÖGLICH: Verbindung wird nicht automatisch getrennt!" >> $PPP_FABALOG
 		exit 1
 	fi
 	$CURRENT_ROUTE
@@ -44,30 +44,30 @@ reanimiert () {
 }
 
 pinger() {
-for SINGLEHOST in $PPP_CHECKHOSTS; do
-	echo -n "$(date): checking $SINGLEHOST" >> $PPP_FABALOG
-	ping -c 1 -W 2 -w 2 -q $SINGLEHOST >/dev/null 2>&1
-	if [ $? -eq 0 ]; then
-		echo " OKAY" >> $PPP_FABALOG
-		if [ -z "$ALIVEIP" ]; then
-			ALIVEIP=$(nslookup $PPP_ALIVECHECK | tail -n1 | tr -s " " | cut -d" " -f3)
-			if [ $? -ne 0 ]; then
-				ALIVEIP=
-			else
-				CURRENT_IF=$(route -n | grep "^0.0.0.0" | tail -n1 | tr -s " " | cut -d " " -f8)
-				CURRENT_GW=$(route -n | grep "^0.0.0.0" | tail -n1 | tr -s " " | cut -d " " -f2)
-				if [ "$CURRENT_GW" != "0.0.0.0" ]; then
-					CURRENT_ROUTE="route add $ALIVEIP gw $CURRENT_GW"
+	for SINGLEHOST in $PPP_CHECKHOSTS; do
+		echo -n "$(date): checking $SINGLEHOST" >> $PPP_FABALOG
+		ping -c 1 -W 2 -w 2 -q $SINGLEHOST >/dev/null 2>&1
+		if [ $? -eq 0 ]; then
+			echo " OKAY" >> $PPP_FABALOG
+			if [ -z "$ALIVEIP" ]; then
+				ALIVEIP=$(nslookup $PPP_ALIVECHECK | tail -n1 | tr -s " " | cut -d" " -f3)
+				if [ $? -ne 0 ]; then
+					ALIVEIP=
 				else
-					[ -n "$CURRENT_IF" ] && CURRENT_ROUTE="route add $ALIVEIP $CURRENT_IF"
+					CURRENT_IF=$(route -n | grep "^0.0.0.0" | tail -n1 | tr -s " " | cut -d " " -f8)
+					CURRENT_GW=$(route -n | grep "^0.0.0.0" | tail -n1 | tr -s " " | cut -d " " -f2)
+					if [ "$CURRENT_GW" != "0.0.0.0" ]; then
+						CURRENT_ROUTE="route add $ALIVEIP gw $CURRENT_GW"
+					else
+						[ -n "$CURRENT_IF" ] && CURRENT_ROUTE="route add $ALIVEIP $CURRENT_IF"
+					fi
+					echo -e "\n$(date): CURRENT_ROUTE: $CURRENT_ROUTE\n"  >> $PPP_FABALOG
 				fi
-				echo -e "\n$(date): CURRENT_ROUTE: $CURRENT_ROUTE\n"  >> $PPP_FABALOG
 			fi
+			return 0
+		else
+			echo " FAIL" >> $PPP_FABALOG
 		fi
-		return 0
-	else
-		echo " FAIL" >> $PPP_FABALOG
-	fi
 	done
 	return 1
 }
