inetd (refs #805)  * /etc/inetd.conf is no longer saved in /tmp/flash (will be generated on startup)  * webinterface: intial support for read-only "files" (buehmann, could you revise it?)  * modinetd: improved support for AVM-daemons (.inetd-files in /var/mod/etc/inetd/) modlibrc: fix occupied ports on restart by:  * modlib_reload: fix wrong returnvalue, default-case added  * modlib_stop: kills all inetd instances now
git-svn-id: http://svn.freetz.org/trunk@5555 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/make/inetd/files/root/usr/bin/modinetd b/make/inetd/files/root/usr/bin/modinetd
--- a/make/inetd/files/root/usr/bin/modinetd
+++ b/make/inetd/files/root/usr/bin/modinetd
@@ -1,21 +1,21 @@
 #!/bin/sh
 #
-# Usage: modinetd [-n] [package]
+# Usage: modinetd [package]
+
+icnf="/var/mod/etc/inetd.conf"
+touch $icnf
 
 usage() {
 	echo "Usage: $(basename $0) [options] [package]..."
 	echo "options:"
 	echo "  -h | --help       - print this help"
-	echo "  -n | --nosave     - do not modsave flash"
 	exit $1
 }
 
 inetd_conf_line() {
 	line="$inetdcfg_port\t$inetdcfg_sock\t$inetdcfg_proto\t$inetdcfg_flags"
 	line="$line\t$inetdcfg_user\t$inetdcfg_exe\t$inetdcfg_arg0 $inetdcfg_args"
-	if [ "$1" = escape ]; then
-		line=$(echo -n "$line" | sed -e 's@/@\\/@g')
-	fi
+	[ "$1" = escape ] && line=$(echo -n "$line" | sed -e 's@/@\\/@g')
 	echo -en "$line"
 }
 
@@ -28,9 +28,8 @@ update_inetd() {
 		exit 1
 	fi
 	echo -n "Updating inetd config for $pkg_name"
-	local icnf="/var/tmp/flash/inetd.conf"
 	. $pkg_path
-	
+
 	if [ "$pkg_name" != "$pkg_subd" ]; then
 		sub_status=$(/etc/init.d/rc.$pkg_name status_$pkg_subd)
 		echo -n " ($pkg_subd)"
@@ -40,7 +39,7 @@ update_inetd() {
 		pkg_inetd=$pkg_name
 	fi
 	echo -n ": "
-	
+
 	if ! grep -q "#:$pkg_inetd:" $icnf; then
 		echo >> $icnf
 		echo "#:$pkg_inetd: $inetdcfg_desc" >> $icnf
@@ -56,12 +55,29 @@ update_inetd() {
 	fi
 }
 
+update_inetd_avm() {
+	local pkg_file=$1
+	local pkg_name=$(echo $pkg_file | sed 's/^.*\///;s/\.inetd$//')
+	local pkg_desc="#:AVM-$pkg_name: AVM $pkg_name daemon"
+	echo -n "Updating inetd config for AVM $pkg_name: "
+	if [ -e $pkg_file ]; then
+		if ! grep -q "^$pkg_desc$" $icnf; then
+			echo >> $icnf
+			echo "$pkg_desc" >> $icnf
+			cat $pkg_file >> $icnf
+		fi
+		echo "active."
+	else
+		sed -i -e "N;/$pkg_desc/b1;b;:1 N;d" $icnf
+		echo "inactive."
+	fi
+}
+
 error() {
 	echo "$0: $*" 1>&2
 }
 
-save=true
-TEMP=$(getopt -o hn --long help,nosave -n "$(basename $0)" -- "$@")
+TEMP=$(getopt -o h --long help -n "$(basename $0)" -- "$@")
 
 [ $? == 0 ] || usage 1
 eval set -- "$TEMP"
@@ -69,33 +85,53 @@ eval set -- "$TEMP"
 while true; do
 	case $1 in
 		-h|--help) usage 0; shift ;;
-		-n|--nosave) save=false; shift ;;
 		--) shift ; break ;;
 		*) echo "Internal error!" ; exit 1 ;;
 	esac
 done
 
 if [ $# -eq 0 ]; then
+	echo 'Configuring inetd:'
+	# Freetz packages
 	for package in $(ls /etc/default.*/*.inetd); do
 		update_inetd $package
 	done
+	# AVM packages
+	for package in $(ls /var/mod/etc/inetd/*.inetd 2>/dev/null); do
+		update_inetd_avm $package
+	done
 else
 	for package; do
-		package_main=$(ls /etc/default.$package/*.inetd)
-		if [ -n "$package_main" ]; then
-			for package_sub in $package_main; do
-				update_inetd "$package_sub"
-			done
+		package_short="$(echo $package|sed 's/AVM-//')"
+		if [ "$package" == "$package_short" ]; then
+			# Freetz packages
+			package_main=$(ls /etc/default.$package/*.inetd 2>/dev/null)
+			if [ -n "$package_main" ]; then
+				for package_sub in $package_main; do
+					update_inetd "$package_sub"
+				done
+			else
+				error "package $package has no default inetd file"
+			fi
 		else
-			error "package $package has no default inetd file"
+			# AVM packages
+			update_inetd_avm /var/mod/etc/inetd/$package_short.inetd
 		fi
 	done
-	
+
 fi
 
-/etc/init.d/rc.inetd reload
-if $save; then
-	/usr/bin/modsave flash
-fi
+# check if we could listen on socket
+grep -vE "^$|^#" $icnf | while read line; do
+	local cleanline="$(echo "$line" | sed 's/\t/ /;s/ */ /;s/^ *//')"
+	local listener=$(echo "$cleanline" | cut -d " " -f1)
+	local ip_proto=$(echo "$cleanline" | cut -d " " -f3)
+	if [ "$(grep -E "$listener[[:space:]]*(stream|dgram|raw|seqpacket)[[:space:]]*$ip_proto" $icnf 2>/dev/null | wc -l)" -gt 1 ]; then
+		echo "WARNING: inetd could not listen on '$listener' multiple times:"
+		grep -E "$listener[[:space:]]*(stream|dgram|raw|seqpacket)[[:space:]]*$ip_proto" $icnf
+	fi
+done
+
+[ "$(/etc/init.d/rc.inetd status)" != "stopped" ] && /etc/init.d/rc.inetd reload
 
 exit 0
diff --git a/root/etc/init.d/modlibrc b/root/etc/init.d/modlibrc
--- a/root/etc/init.d/modlibrc
+++ b/root/etc/init.d/modlibrc
@@ -25,17 +25,17 @@ export LD_LIBRARY_PATH=/mod/lib:/mod/usr/lib
 : ${PID_FILE:=/var/run/${DAEMON_BIN}.pid}
 
 # config:
-#   dummy function if "config" is not defined in parent-script 
+#   dummy function if "config" is not defined in parent-script
 config() { :; }
 
 # stop:
-#   dummy function if "stop" is not defined in parent-script 
+#   dummy function if "stop" is not defined in parent-script
 stop() {
 	return 127
 }
 
 # reload:
-#   dummy function if "reload" is not defined in parent-script 
+#   dummy function if "reload" is not defined in parent-script
 reload() {
 	return 127
 }
@@ -85,20 +85,7 @@ modlib_adduser()
 	fi
 }
 
-# modlib_reload_inetd
-#	check whether /etc/init.d/rc.inetd exists.
-#	reloads inetd. return status
-modlib_reload_inetd()
-{
-	local inetd_rc_script="/etc/init.d/rc.inetd"
-	if [ -x "$inetd_rc_script" ]; then
-		"$inetd_rc_script" reload
-	else
-		killall -HUP inetd
-	fi
-	return $?
-}
-
+#  (#2DO: move to inetd?, only used by rc.ftpd atm, ipv6-support?)
 # modlib_check_port
 #   checks if a port is occupied and by which daemon.
 #	parameters:
@@ -211,33 +198,44 @@ modlib_stop()
 	local fn=$PID_FILE
 	local id=$(cat "$fn" 2>/dev/null)
 	echo -n "Stopping ${DAEMON_LONG_NAME} ... "
-	if ! modlib_check_running; then
-		echo 'not running.'
-		return 0
-	fi
-	stop
-	if [ $? -ne 127 ]; then
-		sleep 1
-	else
-		local cnt=9
-		while [ $cnt -ge 0 ] && kill -0 $id 2>/dev/null; do
-			kill $id 2>/dev/null
-			sleep 1
-			let cnt--
-		done
-		if kill -0 $id 2>/dev/null; then
-			kill -9 $id 2>/dev/null
-			sleep 1
-		fi
-	fi
-	if ! kill -0 $id 2>/dev/null; then
-		rm -f "$fn"
-		echo 'done.'
-		return 0
-	else
-		echo 'failed.'
-		return 1
-	fi
+	modlib_check_running
+	case $? in
+		0)
+			stop
+			if [ $? -ne 127 ]; then
+				sleep 1
+			else
+				local cnt=9
+				while [ $cnt -ge 0 ] && kill -0 $id 2>/dev/null; do
+					kill $id 2>/dev/null
+					sleep 1
+					let cnt--
+				done
+				if kill -0 $id 2>/dev/null; then
+					kill -9 $id 2>/dev/null
+					sleep 1
+				fi
+			fi
+			if ! kill -0 $id 2>/dev/null; then
+				rm -f "$fn"
+				echo 'done.'
+			else
+				echo 'failed.'
+				return 1
+			fi
+			;;
+		3)
+			echo 'not running.'
+			;;
+		5)
+			killall $DAEMON_BIN 2>/dev/null
+			echo 'inetd instances killed, done.'
+			;;
+		*)
+			echo 'status unknown, failed.'
+			return 1
+			;;
+	esac
 }
 
 # modlib_reload
@@ -250,10 +248,10 @@ modlib_reload()
 	echo -n "Reloading ${DAEMON_LONG_NAME} ... "
 	modlib_check_running
 	case $? in
-		1)
+		0)
 			config
 
-			reload 1
+			reload 0
 			local status=$?
 			if [ $status -ne 127 ]; then
 				sleep 1
@@ -281,6 +279,10 @@ modlib_reload()
 			[ $? -eq 127 ] && killall -HUP $DAEMON_BIN 2>/dev/null 1>&2
 			echo 'inetd.'
 			return 0
+			;;
+		*)
+			echo 'status unknown, failed.'
+			return 1
 			;;
 		esac
 }
