Error message for freetz_status; closes #739
git-svn-id: http://svn.freetz.org/trunk@4712 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/root/usr/bin/freetz_status b/root/usr/bin/freetz_status
--- a/root/usr/bin/freetz_status
+++ b/root/usr/bin/freetz_status
@@ -1,6 +1,14 @@
 #!/bin/sh
 
 . /usr/lib/libmodredir.sh
+
+if [ ! -r "/mod/etc/conf/mod.cfg" -o ! -r "/mod/etc/init.d/rc.webcfg" ]; then
+    	CRLF=$'\r\n'
+	echo -n "Content-Type: text/plain${CRLF}${CRLF}"
+	echo "Error[webcfg]: not configured"
+	exit 1
+fi
+
 . /mod/etc/conf/mod.cfg
 
 log=
