* minor spelling improvements
git-svn-id: http://svn.freetz.org/trunk@11292 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/tools/external b/tools/external
--- a/tools/external
+++ b/tools/external
@@ -18,12 +18,12 @@ if [ "$EXTERNAL_DOWNLOADER" == "y" ]; then
 	else
 		echo1 "creating directory \"$(pwd)/$OUT_DIR\" for outsourced files"
 		mkdir $OUT_DIR
-		[ $? -ne 0 ] && error 1 "$MESSAGE Directory \"$OUT_DIR\" can not be created"
+		[ $? -ne 0 ] && error 1 "$MESSAGE Directory \"$OUT_DIR\" cannot be created"
 	fi
 	if [ -e "$OUT_DIR/$OUT_CONF" ]; then
 		echo1 "removing old Downloader configuration file $OUT_DIR/$OUT_CONF"
 		rm "$OUT_DIR/$OUT_CONF"
-		[ $? -ne 0 ] && error 1 "$MESSAGE $OUT_DIR/$OUT_CONF can not be deleted"
+		[ $? -ne 0 ] && error 1 "$MESSAGE $OUT_DIR/$OUT_CONF cannot be deleted"
 	fi
 	echo1 "creating new Downloader configuration file $OUT_DIR/$OUT_CONF"
 	touch "$OUT_DIR/$OUT_CONF"
@@ -97,7 +97,7 @@ for EXTERNAL_FILE in $EXTERNAL_FILES; do
 			FILEPERM=$(ls -l $EXTERNAL_TEMP | awk '{k=0;for(i=0;i<=8;i++)k+=((substr($1,i+2,1)~/[rwx]/)*2^(8-i));if(k)printf("%0o",k)}')
 			echo2 "packing $FILENAME.gz for Downloader"
 			gzip -c "$EXTERNAL_TEMP" > "$OUT_DIR/$FILENAME.gz"
-			[ $? -ne 0 ] && error 1 "$MESSAGE $OUT_DIR/$FILENAME.gz can not be created"
+			[ $? -ne 0 ] && error 1 "$MESSAGE $OUT_DIR/$FILENAME.gz cannot be created"
 		fi
 		#move file
 		if [ `ls "$EXTERNAL_TEMP" 2>/dev/null | wc -l` -gt 0 ]; then
