* Add curl to external  * Add libcrypto to external  * Add option to create .gz files for Downloader  (by hermann72pb)
git-svn-id: http://svn.freetz.org/trunk@2605 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/tools/external b/tools/external
--- a/tools/external
+++ b/tools/external
@@ -6,12 +6,45 @@ fi
 EXTERNAL_DIRECTORY=`echo $EXTERNAL_DIRECTORY|sed 's/\/*$//'`
 mkdir -p "${EXTERNAL_MOD_DIR}"
 
+#preparation for Downloader outsourcing
+OUT_DIR="outboard"
+OUT_CONF="downloader.conf"
+ERROR="EXTERNAL SCRIPT ERROR:"
+WARNING="EXTERNAL SCRIPT WARNING:"
+if [ "$EXTERNAL_DOWNLOADER" == "y" ]; then
+	if [ -e "$OUT_DIR" ]; then
+		[ "$FREETZ_VERBOSITY_LEVEL" -ge 1 ] && echo "  \"$(pwd)/$OUT_DIR\" is used as directory for outsourced files"
+		[ "$FREETZ_VERBOSITY_LEVEL" -ge 1 ] && echo "  all existing files in this directory will be rewritten"
+	else
+		[ "$FREETZ_VERBOSITY_LEVEL" -ge 1 ] && echo "  creating directory \"$(pwd)/$OUT_DIR\" for outsourced files"
+		mkdir $OUT_DIR
+		TMPERR=$?
+		if [ $TMPERR -eq 1 ]; then
+			echo "$ERROR Directory \"$OUT_DIR\" can not be created"
+			exit 1
+		fi 
+	fi
+	if [ -e "$OUT_DIR/$OUT_CONF" ]; then
+		echo "  removing old Downloader configuration file $OUT_DIR/$OUT_CONF"
+		rm "$OUT_DIR/$OUT_CONF"
+		TMPERR=$?
+		if [ $TMPERR -eq 1 ]; then
+			echo "$ERROR $OUT_DIR/$OUT_CONF can not be deleted"
+			exit 1
+		fi 
+	fi
+	echo "  creating new Downloader configuration file $OUT_DIR/$OUT_CONF"
+	touch "$OUT_DIR/$OUT_CONF"
+fi
+
 EXTERNAL_FILES="$EXTERNAL_OWN_FILES"
 [ "$EXTERNAL_FREETZ_PACKAGE_OPENVPN" == "y" ] && EXTERNAL_FILES+=" /usr/sbin/openvpn"
+[ "$EXTERNAL_FREETZ_PACKAGE_CURL" == "y" ] && EXTERNAL_FILES+=" /usr/bin/curl /usr/lib/libcurl.so.4.0.1"
 [ "$EXTERNAL_FREETZ_PACKAGE_BASH" == "y" ] && EXTERNAL_FILES+=" /bin/bash"
 [ "$EXTERNAL_FREETZ_PACKAGE_BLUEZ_UTILS" == "y" ] && EXTERNAL_FILES+=" /usr/bin/dund /usr/bin/pand /usr/bin/rfcomm /usr/bin/l2ping /usr/bin/sdptool /usr/sbin/hcid /usr/sbin/sdpd /usr/sbin/hciconfig /usr/sbin/hcitool"
 [ "$EXTERNAL_FREETZ_PACKAGE_LTRACE" == "y" ] && EXTERNAL_FILES+=" /usr/sbin/ltrace"
 [ "$EXTERNAL_FREETZ_LIB_libart_lgpl_2" == "y" ] && EXTERNAL_FILES+=" /usr/lib/libart_lgpl_2.so.2.3.19"
+[ "$EXTERNAL_FREETZ_LIB_libcrypto" == "y" ] && EXTERNAL_FILES+=" /usr/lib/libcrypto.so.0.9.8"
 [ "$EXTERNAL_FREETZ_LIB_libdevmapper" == "y" ] && EXTERNAL_FILES+=" /usr/lib/libdevmapper.so.1.02"
 [ "$EXTERNAL_FREETZ_LIB_libelf" == "y" ] && EXTERNAL_FILES+=" /usr/lib/libelf.so.0.8.10"
 [ "$EXTERNAL_FREETZ_LIB_libfreetype" == "y" ] && EXTERNAL_FILES+=" /usr/lib/libfreetype.so.6.3.16"
@@ -51,6 +84,10 @@ EXTERNAL_FILES="$EXTERNAL_OWN_FILES"
 EXTERNAL_FILES="`echo $EXTERNAL_FILES|sed 's/ / \//g;s/\/\/*/\//g'`"
 
 for EXTERNAL_FILE in $EXTERNAL_FILES; do
+	FILENAME=$(basename $EXTERNAL_FILE)
+	if [ -L "${FILESYSTEM_MOD_DIR}$EXTERNAL_FILE" ]; then
+		[ "$FREETZ_VERBOSITY_LEVEL" -ge 1 ] && echo "$WARNING ${FILESYSTEM_MOD_DIR}$EXTERNAL_FILE is a symbolic link. It will not be outsourced"
+	else
 	EXTERNAL_LINKSUBDIR=""
 	EXTERNAL_TARGETDIR="${EXTERNAL_MOD_DIR}"
 	if [ "$EXTERNAL_SUBDIRS" == "y" ]; then
@@ -59,16 +96,35 @@ for EXTERNAL_FILE in $EXTERNAL_FILES; do
 		mkdir -p "$EXTERNAL_TARGETDIR"
 	fi
 	EXTERNAL_TEMP="${FILESYSTEM_MOD_DIR}$EXTERNAL_FILE"
+        if [ "$EXTERNAL_DOWNLOADER" == "y" ]; then
+            FILEPERM=$(ls -l $EXTERNAL_TEMP | awk '{k=0;for(i=0;i<=8;i++)k+=((substr($1,i+2,1)~/[rwx]/)*2^(8-i));if(k)printf("%0o",k)}')
+			[ "$FREETZ_VERBOSITY_LEVEL" -ge 1 ] && echo "  packing $FILENAME.gz for Downloader"
+			gzip -c "$EXTERNAL_TEMP" > "$OUT_DIR/$FILENAME.gz"
+			TMPERR=$?
+			if [ $TMPERR -eq 1 ]; then
+				echo "$ERROR $OUT_DIR/$FILENAME.gz can not be created"
+				exit 1
+			fi
+        fi
 	if [ `ls "$EXTERNAL_TEMP" 2>/dev/null | wc -l` -gt 0 ]; then
 		mv "$EXTERNAL_TEMP" "$EXTERNAL_TARGETDIR/"
 		EXTERNAL_MSG="moved"
+            if [ "$EXTERNAL_DOWNLOADER" == "y" ]; then
+                echo "$FILENAME $FILEPERM $EXTERNAL_DIRECTORY$EXTERNAL_LINKSUBDIR" >> $OUT_DIR/$OUT_CONF
+            fi
 	else
 		EXTERNAL_MSG="not found"
 	fi
-	ln -s "$EXTERNAL_DIRECTORY$EXTERNAL_LINKSUBDIR/$(basename $EXTERNAL_FILE)" "${FILESYSTEM_MOD_DIR}$EXTERNAL_FILE"
+        ln -s "$EXTERNAL_DIRECTORY$EXTERNAL_LINKSUBDIR/$FILENAME" "${FILESYSTEM_MOD_DIR}$EXTERNAL_FILE"
 	[ "$FREETZ_VERBOSITY_LEVEL" -ge 1 ] && echo "  $EXTERNAL_FILE... $EXTERNAL_MSG & linked"
+    fi    
 done
 echo "$EXTERNAL_DIRECTORY" > "${EXTERNAL_MOD_DIR}/.external"
-
-[ "$EXTERNAL_CREATEPAK" == "y" ] || echo "  NOTE: Please copy content of build/modified/external/ to $EXTERNAL_DIRECTORY on your box BEFORE you flash the reduced image"
-
+if [ "$EXTERNAL_DOWNLOADER" == "y" ]; then
+	echo "  NOTE: Please upload gezipped Downloader files from"
+	echo "        \"$(pwd)/$OUT_DIR\" to your http or ftp server"
+	echo "        and copy the Downloader configuration from"
+	echo "        \"$(pwd)/$OUT_DIR/$OUT_CONF\" into Downloader WEBUI"
+else
+	[ "$EXTERNAL_CREATEPAK" == "y" ] || echo "  NOTE: Please copy content of build/modified/external/ to $EXTERNAL_DIRECTORY on your box BEFORE you flash the reduced image"
+fi
