fwmod:  * be a little bit more friendly to the users of the Freetz framework using it just to repack the firmware without actually adding Freetz to it  * add {{{all_no_freetz}}} hook to fwmod_custom - invoked if {{{"STEP 2: MODIFY"}}} is omitted  * add examples to fwmod_custom::all_no_freetz showing how to restore the {{{telnet}}} resp. the {{{debug.cfg}}} support (both disabled by default)
Note:
 * signing firmware feature of fwmod (-s option) could also be used in the "no freetz"-mode, this will make it possible to update custom Fritz!OS-6.5x based firmwares without the need to downgrade to Fritz!OS-6.3x before (provided every new custom firmware is signed with exactly the same key as that on the box)


git-svn-id: http://svn.freetz.org/trunk@13796 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/tools/freetz_functions b/tools/freetz_functions
--- a/tools/freetz_functions
+++ b/tools/freetz_functions
@@ -476,6 +476,30 @@ collect_pkg_files()
 }
 
 #
+# checks if fwmod_custom script exists, has correct syntax, and invokes it
+# with exactly the same parameters as those passed to invoke_fwmod_custom itself
+#
+invoke_fwmod_custom()
+{
+	if [ -x "${BASE_DIR}/fwmod_custom" ]; then
+		echo "invoking custom script"
+
+		# syntax check
+		$SHELL -n "${BASE_DIR}/fwmod_custom"
+
+		if [ $? -ne 0 ]; then
+			error 1 "syntax error in fwmod_custom script"
+		fi
+
+		( cd "$MOD_DIR" && ../../fwmod_custom "$@" ) || exit 1
+
+		if [ $? -ne 0 ]; then
+			error 1 "fwmod_custom script returned error"
+		fi
+	fi
+}
+
+#
 # Returns "(NEEDED)"-entries for all binaries/libraries supplied
 #
 getNeededEntries()
