[test-branch]:  * First step of silencing build (packages, libraries)  * Print yellow error messages  * refs #562
git-svn-id: http://svn.freetz.org/branches/test-branch@4182 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/tools/freetz_functions b/tools/freetz_functions
--- a/tools/freetz_functions
+++ b/tools/freetz_functions
@@ -81,7 +81,7 @@ echo2()
 error()
 {
 	if [ "$1" -gt 0 ]; then
-		echo -e "ERROR: $2" 1>&2
+		echo -e "${__Y}ERROR: $2${__N}" 1>&2
 		exit $1
 	fi
 }
