modsed:  * be very restrictive - fail immediately on any of the 'sed: -e expression #1'-errors  * refs #2274
git-svn-id: http://svn.freetz.org/trunk@11342 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/tools/freetz_functions b/tools/freetz_functions
--- a/tools/freetz_functions
+++ b/tools/freetz_functions
@@ -106,7 +106,7 @@ modsed()
 	esac
 	if [ -f "$2" ]; then
 		echo2 "patching $2"
-		sed -i -e "$1" "$2"
+		sed -i -e "$1" "$2" || error 1 "modsed failed editing $2 (bad sed syntax?)"
 		if [ $# -ge 3 ]; then
 			grep -q "$3" "$2" || error 1 "modsed failed editing $2"
 		fi
