linkbox_remove-function:  * revise it, make it work with the latest labors for 7390 & 7490  * fixes the problem reported in [http://www.ip-phone-forum.de/showthread.php?t=271048 this thread]
git-svn-id: http://svn.freetz.org/trunk@12172 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/tools/freetz_functions b/tools/freetz_functions
--- a/tools/freetz_functions
+++ b/tools/freetz_functions
@@ -3,9 +3,21 @@
 #linkbox_remove <menu-name>
 #removes links within a box on the left
 linkbox_remove() {
-	local linkbox_file="${HTML_LANG_MOD_DIR}/templates/menu_page_head.html"
-	local linkbox_row=$(cat $linkbox_file |nl| sed -n "s/^ *\([0-9]*\).*menu.write_menu('$1')$/\1/p")
-	modsed "$((linkbox_row-6)),$((linkbox_row+9))d" $linkbox_file
+	# - removes all lines within the following lua-code-block:
+	#   if menu.show_addition_menu("$menuname") then
+	#   ...
+	#   end
+	# - assumes the 1st "end" following "if menu..." is the closing "end" of this "if",
+	#   i.e. no other if's are started within the block
+#	modsed -r \
+#	  "/^[ \t]*if[ \t]+menu[.]show_additional_menu[(]([\"'])$1\1[)][ \t]+then[ \t]*$/,/^[ \t]*end[ \t]*$/ d" \
+#	  "${HTML_LANG_MOD_DIR}/templates/menu_page_head.html"
+
+	# alternative (a more safe) version: instead of removing the block like the version above
+	# it replaces "if menu.show_addition_menu("$menuname") then" with "if false then"
+	modsed -r \
+	  "s,(menu[.]show_additional_menu[(]([\"'])$1\2[)]),false and \1," \
+	  "${HTML_LANG_MOD_DIR}/templates/menu_page_head.html"
 }
 
 #quickstart_remove <target-link>
@@ -97,6 +109,13 @@ rm_files()
 #should be used instead of sed -i -e in patch scripts
 modsed()
 {
+	local extended_regexp=""
+
+	if [ "$1" == "-r" ]; then
+		extended_regexp="$1"
+		shift
+	fi
+
 	[ $# -le 1 ] && error 1 "modsed failed, not enough parameters."
 	case $2 in
 		#since firmware 05.55 HTML_SPEC_MOD_DIR does not exist anymore
@@ -104,7 +123,7 @@ modsed()
 	esac
 	if [ -f "$2" ]; then
 		echo2 "patching $2"
-		sed -i -e "$1" "$2" || error 1 "modsed failed editing $2 (bad sed syntax?)"
+		sed -i $extended_regexp -e "$1" "$2" || error 1 "modsed failed editing $2 (bad sed syntax?)"
 		if [ $# -ge 3 ]; then
 			grep -q "$3" "$2" || error 1 "modsed failed editing $2"
 		fi
