modsed:  * extended by a optional third parameter (grep syntax) to verify the sed  * the grep has to succeed if the 3rd parameter is set or the script aborts
git-svn-id: http://svn.freetz.org/trunk@6634 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/tools/freetz_functions b/tools/freetz_functions
--- a/tools/freetz_functions
+++ b/tools/freetz_functions
@@ -54,13 +54,21 @@ rm_files()
 #another little helper
 modsed()
 {
-#modsed <expression> <file>
+#modsed <sed-expression> <file> [grep-expression-to-verify-sed]
 #should be used instead of sed -i -e in patch scripts
+	[ $# -le 1 ] && error 1 "modsed failed, not enough parameters."
 	if [ -f "$2" ]; then
 		echo2 "patching $2"
 		sed -i -e "$1" "$2"
+		if [ $# -ge 3 ]; then
+			grep -q "$3" "$2" || error 1 "modsed failed editing $2"
+		fi
 	else
-		warn "$2 not found, skipping"
+		if [ $# -lt 3 ]; then
+			warn "$2 not found, skipping."
+		else
+			error 1 "$2 not found, aborting."
+		fi
 	fi
 }
 
