Fix debug output and beautify URL and file name printing
git-svn-id: http://svn.freetz.org/trunk@7614 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/tools/freetz_download b/tools/freetz_download
--- a/tools/freetz_download
+++ b/tools/freetz_download
@@ -41,16 +41,16 @@ do_download()
 {
   # $1 = target directory, $2 = full download URL
   echo
-  if [ "$DEBUG" == "1" ]; then echo "wget -nd -T 20 -t 3 --no-check-certificate --passive-ftp -P $1 $2"; fi
+  if [ "$DEBUG" == "1" ]; then echo "wget -nd -t3 --timeout=20 --no-check-certificate --passive-ftp -P \"$1\" \"$2\""; fi
   wget -nd -t3 --timeout=20 --no-check-certificate --passive-ftp -P "$1" "$2"
   wget_result=$?
   if [ "$wget_result" != "0" ]; then
-    echo "Download failed - $2  ->  error code $wget_result" >&2
+    echo "Download failed - \"$2\"  ->  error code $wget_result" >&2
     fname=$(basename $2)
     rm -f $1/$fname
     return $wget_result
   fi
-  echo "Download succeeded - $2  ->  saved to folder $1"
+  echo "Download succeeded - \"$2\"  ->  saved to folder \"$1\""
 }
 
 do_check()
@@ -115,11 +115,11 @@ MD5="$4"
 
 if [ "$DEBUG" == "1" ]; then
   echo "freetz_download parameters:"
-  echo "  DL_DIR=$1"
+  echo "  DL_DIR=$DL_DIR"
   echo "  DOT_CONFIG=$DOT_CONFIG"
-  echo "  DL_FILE=$3"
-  echo "  MAIN_URL=$4"
-  echo "  MD5=$5"
+  echo "  DL_FILE=$DL_FILE"
+  echo "  MAIN_URL=$MAIN_URL"
+  echo "  MD5=$MD5"
 fi
 
 num_sites=0
