merge in r2593:r2595, r2597:r2598, r2601:r2604, r2606:r2617, r2619:r2621, r2623:r2625, r2627:r2628, r2630:r2632, r2635, r2637:r2644, r2647:r2644, r2647:r2653, r2656 from trunk:  * firmware version bumps:   * 7170 Labor All In One 29.04.63-12537   * 7170 Labor DSL 29.04.99-12526   * 7270 54.04.59   * 7270 Labor All In One 54.04.63-12461   * 7270 Labor DSL 54.04.99-12606   * 7141: 40.04.59-11763   * 7170: 29.04.59-11763   * 7270: 59.04.59-11779   * 7140 and 7170 English XX.04.57  * package version bumps:   * busybox 1.11.3   * curl 7.19.0   * devmapper 1.02.27   * avm-firewall 2.0.4_rc1   * module-init-tools 3.4   * ntfs-3g 1.5012   * obexftp 0.22   * openssl 0.9.8i   * openvpn 2.1_rc13   * privoxy 3.0.10   * ruby 1.8.7   * sg3_utils 1.26   * wget 1.11.4  * kernel:   * 2.6.19.2: use other net sched timer (AVM changed it)  * fixes:   * show complete firmware version as it looks strange when disabling FREETZ_SUBVERSION_STRING   * implemented swap file creation via web interface   * made save.cgi restart swap on save if running   * store freetz-version in firmware (etc.freetz-version) even if FREETZ_SUBVERSION_STRING is not set   * fix error in libmodcgi.sh (get_env was not defined and is now no longer necessary)   * revert change from r2203: FON WLAN: WLAN doesn't work with sources newer then 04.33   * fix patches for AiO 7170   * change download url of sysfsutils   * change download url (original was very slow)   * fix wrong wget version in menuconfig   * Add missing clean targets for download-toolchain   * transmission:    * add TARGET_CFLAGS and _CXXFLAGS to reduce binary size    * add transmission-daemon and -remote   * check-builddir-version no longer complains if no .config is present   * made fwmod work correctly if SHELL is not /bin/bash   * Fix wrong name of /etc/default directory for W900V Alien   * W900V Alien: Fix wrong CONFIG_PRODUKT in rc.conf   * usbroot: Revert r2495 as /dev is always writeable  * other:
  * small Makefile cleanup
  * update tools/mklibs.py with some uclibc specific things
  * make/Makefile.in: Use DL_TOOL variable
  * Use DL_TOOL for tools and toolchain
  * Add MD5 check for tools and some of toolchain downloads
  * Add .defconfig file because it is needed for noconfig target tools and freetz_download
  * privoxy: use pthreads
 * Makefile: 
  * moved uclibc-check to own make-target
  * integrated 2 variables to skip uclibc- and prerequisite-check
  * implemented new (default) target check-lastbuild-version to check if svn version was updated since last build and force update of .config 
  * push_firmware now supports flashing directly from 'real' firmware images (by unpacking to tempfile) 

git-svn-id: http://svn.freetz.org/branches/freetz-stable-1.0@2657 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/tools/push_firmware b/tools/push_firmware
--- a/tools/push_firmware
+++ b/tools/push_firmware
@@ -5,8 +5,8 @@
 # Flash kernel image (hidden root) to Fritz!Box or Speedport.
 # Works on Linux (main platform) and Cygwin (inofficially).
 #
-# Copyright (c) 2007 Michael Hampicke    (mike@mhampicke.de)
-#               2007 Alexander Kriegisch (kriegaex, ip-phone-forum.de)
+# Copyright (c) 2007 Michael Hampicke	 (mike@mhampicke.de)
+#		2007 Alexander Kriegisch (kriegaex, ip-phone-forum.de)
 #
 # Cygwin users note:
 #   1. There is NO guarantee whatsoever that this will work on Cygwin, even
@@ -26,7 +26,7 @@
 #
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
@@ -41,8 +41,8 @@ function push_fw() {
 
 	echo
 	echo " * You should now reboot your box."
-	echo "   Waiting for box to shut down."
-	echo "   Tip: switch off, if reboot is not detected because it happens too quickly"
+	echo "	 Waiting for box to shut down."
+	echo "	 Tip: switch off, if reboot is not detected because it happens too quickly"
 	echo -n "   "
 	while eval "ping $ping_params $ip > /dev/null"; do
 		echo -n "."
@@ -52,7 +52,7 @@ function push_fw() {
 
 	echo
 	echo " * No reply from box. Assuming switch-off or restart."
-	echo "   Trying to re-detect box."
+	echo "	 Trying to re-detect box."
 	echo -n "   "
 	while ! eval "ping $ping_params $ip > /dev/null"; do
 		echo -n "."
@@ -62,8 +62,8 @@ function push_fw() {
 
 	echo
 	echo " * Box is back up again."
-	echo "   Initiating transfer."
-	echo "   Tip: switch off/on box several times, if FTP client cannot log in ..."
+	echo "	 Initiating transfer."
+	echo "	 Tip: switch off/on box several times, if FTP client cannot log in ..."
 	echo
 
 	if [ $FOUND_NCFTP ]; then
@@ -94,33 +94,48 @@ if [ -z "$1" ]; then
 	echo
 	echo "Usage: $0 <firmware> [ -f ] [ <ip> ]"
 	echo ""
-	echo "firmware    firmware file to flash (mostly kernel.image)"
-	echo "-f          disable safety prompt"
-	echo "ip          bootloader IP address (default: 192.168.178.1)"
+	echo "firmware	  firmware file to flash (mostly kernel.image)"
+	echo "-f	  disable safety prompt"
+	echo "ip	  bootloader IP address (default: 192.168.178.1)"
 	echo
 	exit 1
 fi
 
 img=""
-if [ "$(uname -s)" == "Darwin" ]; then
-  hexdump -n4 "$1" | grep -iq "81 12 ed fd" && img="$1"
-else
-  hexdump -n4 "$1" | grep -iq "1281 feed" && img="$1"
-fi
-if [ -z "$img" ]; then
-	echo >&2
-	echo "Error: file is not a valid image to be written to mtd1. Please use a" >&2
-	echo "hidden root 'kernel.image' containing both Linux kernel and file system." >&2
-	if tar tf "$1" ./var/tmp/kernel.image > /dev/null 2>&1; then
-		echo >&2
-		echo "Hint: file seems to be a full firmware image archive in 'tar' format" >&2
-		echo "containing the 'kernel.image' you are looking for. Please extract the archive" >&2
-		echo "by means of 'tar xf', then call this script again upon the extracted " >&2
-		echo "'kernel.image'." >&2
-	fi
-	echo >&2
+basename=$(basename $0)
+[ -e "$1" ] || { echo "$basename: $1: No such file or directory."; exit 1; }
+[ -f "$1" ] || { echo "$basename: $1: Not a file."; exit 1; }
+[ -r "$1" ] || { echo "$basename: $1: Access denied."; exit 1; }
+
+function cleanup() {
+	[ -n "$tmpimg" -a -f "$tmpimg" ] && rm -rf "$tmpimg";
 	exit 1
-fi
+}
+
+trap cleanup EXIT SIGTERM SIGINT
+arg1=$1
+while [ -z "$img" ]; do
+	if [ "$(uname -s)" == "Darwin" ]; then
+		hexdump -n4 "$arg1" | grep -iq "81 12 ed fd" && img="$arg1"
+	else
+		hexdump -n4 "$arg1" | grep -iq "1281 feed" && img="$arg1"
+	fi
+	if [ -z "$img" ]; then
+		if tar tf "$arg1" ./var/tmp/kernel.image > /dev/null  2>&1; then
+			tmpimg=$(mktemp -t) || { echo "$basename: Error creating temporary fil."; exit 1; }
+			echo >&2
+			echo "Hint: file seems to be a full firmware image archive in 'tar' format" >&2
+			echo "containing the 'kernel.image'. Now trying to unpack and use that image." >&2
+			tar -Oxf "$arg1" ./var/tmp/kernel.image > $tmpimg
+			arg1=$tmpimg
+		else
+			echo >&2
+			echo "Error: file is not a valid image to be written to mtd1. Please use a" >&2
+			echo "hidden root 'kernel.image' containing both Linux kernel and file system." >&2
+			exit 1
+		fi
+	fi
+done
 
 ping_params="-c1 -w1"
 if [ "$(uname -o)" == "Cygwin" ]; then
