inetd (refs #805)  * inetd doesn't collect *.inetd files at startup anymore  * every package registers itself at startup (packages with disabled inetd won't register anymore)  * remove not longer needed logfile  * logfile-coloring adapted
git-svn-id: http://svn.freetz.org/trunk@5614 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/root/etc/init.d/modlibrc b/root/etc/init.d/modlibrc
--- a/root/etc/init.d/modlibrc
+++ b/root/etc/init.d/modlibrc
@@ -239,14 +239,19 @@ modlib_startdaemon()
 modlib_start()
 {
 	local DAEMON_ENABLED=$1
-	if [ "$DAEMON_ENABLED" == "no" -o "$DAEMON_ENABLED" == "inetd" -a -x /etc/init.d/rc.inetd ]; then
-		if [ "$DAEMON_ENABLED" != "inetd" ]; then
-			echo "${DAEMON_LONG_NAME} is disabled." 1>&2
-		else
-			echo "${DAEMON_LONG_NAME} is started via inetd." 1>&2
-			config
-		fi
+	if [ "$DAEMON_ENABLED" == "no" ]; then
+		echo "${DAEMON_LONG_NAME} is disabled." 1>&2
 		exit 1
+	fi
+	if [ "$DAEMON_ENABLED" == "inetd" ]; then
+		if [ ! -x /etc/init.d/rc.inetd ]; then
+			echo "${DAEMON_LONG_NAME} could not find inetd, failed." 1>&2
+			exit 1
+		else
+			config
+			/etc/init.d/rc.inetd config $DAEMON
+			exit
+		fi
 	fi
 
 	modlib_check_running
