rc.dsld:  * preservers cmdargs now  * uses modlib functions  * modlib_startdaemon not usable because dsld needs env!? modlibrc  * another fail-check added (refs #834)
git-svn-id: http://svn.freetz.org/trunk@5082 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/root/etc/init.d/modlibrc b/root/etc/init.d/modlibrc
--- a/root/etc/init.d/modlibrc
+++ b/root/etc/init.d/modlibrc
@@ -313,6 +313,10 @@ modlib_startdaemon()
 	local fn=${PID_FILE-/var/run/$DAEMON.pid}
 	if [ ! -s "$fn" ]; then
 		local dp=`pidof -s ${DAEMON_BIN-$DAEMON}`
+		if [ "$?" -ne 0 ]; then
+			echo 'failed.'
+			exit 1
+		fi
 		[ -n "$dp" ] && echo "$dp" > $fn
 	fi
 	
@@ -324,7 +328,6 @@ modlib_startdaemon()
 #    function "start" must be defined in the calling script
 #    $1: value for DAEMON_ENABLED
 #    returns: 0=success or 1=error
-#    if available runs "config" of rc.$DAEMON
 modlib_start()
 {
 	local DAEMON_ENABLED="$1"
