inetd (refs #805)  * if a package is configured for inetd, but inetd is not available: behave like in "automatic"-mode vsftpd:  * fix for inetd: get _ENABLED by using modlib_status
git-svn-id: http://svn.freetz.org/trunk@5615 f5190166-0702-4917-9039-51ec32eddaf5

diff --git a/root/etc/init.d/modlibrc b/root/etc/init.d/modlibrc
--- a/root/etc/init.d/modlibrc
+++ b/root/etc/init.d/modlibrc
@@ -181,7 +181,9 @@ modlib_check_port()
 modlib_check_running()
 {
 	[ -n "$FORCE_STATUS" ] && return $FORCE_STATUS
-	[ "$(eval echo \$$(echo ${CONF_ENABLED} | tr [:lower:]- [:upper:]_))" == "inetd" ] && return 5
+	if [ -x /etc/init.d/rc.inetd ]; then
+		[ "$(eval echo \$$(echo ${CONF_ENABLED} | tr [:lower:]- [:upper:]_))" == "inetd" ] && return 5
+	fi
 	if [ -n "$DAEMON_CHECK" ]; then
 		for DAEMON_single in $DAEMON_CHECK; do
 			pidof $DAEMON_single >/dev/null 2>&1 || return 3
@@ -245,8 +247,7 @@ modlib_start()
 	fi
 	if [ "$DAEMON_ENABLED" == "inetd" ]; then
 		if [ ! -x /etc/init.d/rc.inetd ]; then
-			echo "${DAEMON_LONG_NAME} could not find inetd, failed." 1>&2
-			exit 1
+			echo "WARNING: ${DAEMON_LONG_NAME} could not find inetd." 1>&2
 		else
 			config
 			/etc/init.d/rc.inetd config $DAEMON
